### ISSUE TITLE
make tests failing with error "could not read Username for 'https://github.com': terminal prompts disabled"

### ISSUE THREAD

**Issue by aditijadhav38** [weaveworks/scope#3820] opened 2020-10-07 10:23 UTC
## What happened?
Facing error `could not read Username for 'https://github.com': terminal prompts disabled` while running tests form `tools/test` on x86_64.

## How to reproduce it?
Steps performed:
1.Downloaded Go-1.15.2
2.Clone scope Github [Repository](https://github.com/weaveworks/scope.git)
3.Git checkout 1.13.1
4.Build scope using `make` command
5.Run unit tests using `make tests` command

## Anything else we need to know?
scope has built successfully and scope probe has started successfully. Issue faced only while running tests.

## Versions:
```
$ scope version
Weave Scope version 2f9ccdc8
$ docker version
19.03.6
```
## Logs:
```
$ uname -a
Linux masons1.fyre.ibm.com 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
$ docker logs weavescope
warning: I'm not PID 1, I'm PID 624601
/sbin/runsvdir started
time="2020-10-06T12:13:37Z" level=info msg="publishing to: 127.0.0.1:4040"
<probe> INFO: 2020/10/06 12:13:37.033279 Basic authentication disabled
<probe> INFO: 2020/10/06 12:13:37.059622 command line args: --mode=probe --probe.docker=true
<app> INFO: 2020/10/06 12:13:37.065230 app starting, version 2f9ccdc8, ID 563ca45bff277239
<app> INFO: 2020/10/06 12:13:37.065306 command line args: --mode=app --probe.docker=true
<probe> INFO: 2020/10/06 12:13:37.075758 probe starting, version 2f9ccdc8, ID 11ac34750b049e00
<app> INFO: 2020/10/06 12:13:37.098879 Basic authentication disabled
<probe> WARN: 2020/10/06 12:13:37.099652 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: connect: connection refused
<probe> ERRO: 2020/10/06 12:13:37.120102 Error fetching app details: Get http://127.0.0.1:4040/api: dial tcp 127.0.0.1:4040: connect: connection refused
<app> INFO: 2020/10/06 12:13:37.203983 listening on :4040
<app> WARN: 2020/10/06 12:13:37.642287 Error updating weaveDNS, backing off 20s: Error running weave ps: exit status 1: "Link not found\n". If you are not running Weave Net, you may wish to suppress this warning by launching scope with the `--weave=false` option.
<probe> INFO: 2020/10/06 12:13:38.131459 Control connection to 127.0.0.1 starting
<probe> WARN: 2020/10/06 12:13:40.781159 Error setting up the eBPF tracker, falling back to proc scanning: failed to init perf map for IPv4 events: error guessing offsets: invalid guessing state while guessing destination address IPv6, got checking expected checked
```

**Comment by bboreham** [comment] 2020-10-08 11:37
It's possible this is caused by some changes in upstream dependencies since v1.13.1 was released.
Could you try the build again on master, and if it still fails show the whole transcript please?

**Comment by bboreham** [comment] 2020-12-29 18:21
Closing as unanswered

**Closed by bboreham** 2020-12-29 18:21 UTC

**Comment by aditijadhav38** [comment] 2021-01-29 07:05
@bboreham Sorry for the late response. I have tried building again on master branch, make test command ran successfully. Could you please let me know will this be fixed in next scope release. Because it still failed for v1.13.1

**Comment by bboreham** [comment] 2021-01-29 10:54
No specific plan.

Why do you need tests to run on a release version?

**Comment by aditijadhav38** [comment] 2021-01-29 12:17
@bboreham I am working on verifying the releases on s390x so we usually run tests for latest stable release.
