### ISSUE TITLE
scope tells me it's available at URLs that it's not available at

### ISSUE THREAD

**Issue by jml** [weaveworks/scope#1678] opened 2016-07-14 12:53 UTC
Running scope 0.16.1 on my Mac using docker-machine, I see the following:

```
$ ./scope launch
c46ebb9bc663573b9ca39000352cba4da5184c5ad61c9450f39ad37757298527
Weave Scope is reachable at the following URL(s):
  * http://10.32.0.1:4040/
  * http://192.168.99.100:4040/
  * http://10.0.2.15:4040/
```

However, when I click on these URLs, I get "address unreachable" errors for the first and third. Only the second URL is accessible.

Ideally, Scope would only tell me about URLs that I can actually reach. Failing that, the wording should be amended to be more truthful.

**Comment by tomwilkie** [comment] 2016-07-14 13:41
Dupe of #1190

**Comment by tomwilkie** [comment] 2016-07-14 13:42
Maybe not a dupe actually.  But related.

**Comment by 2opremio** [comment] 2016-09-08 10:14
> Ideally, Scope would only tell me about URLs that I can actually reach. Failing that, the wording should be amended to be more truthful.

We should change the wording then, since the _URLs that I can actually reach_ also depend on where you are connecting from (including firewalls and what not) and Scope cannot know about that.

**Comment by rade** [comment] 2017-08-03 10:32
> We should change the wording then, since the _URLs that I can actually reach_ also depend on where you are connecting from (including firewalls and what not) and Scope cannot know about that.

I don't think that this a big deal, but sure if we can make a small tweak to the wording (w/o turning it into a novel) then fine.

The main issue jml reported is that even for a purely local setup, scope may show a bunch of addresses that don't work. It would be nice if we were able to filter those out somehow.

**Comment by rade** [comment] 2017-08-03 10:34
IMO fixing this is only worthwhile if we can come up with a fairly clean and short solution.

**Closed** 2017-08-14 16:20 UTC
Labels: accuracy, bug
