### ISSUE TITLE
bouncing the probe garbles view

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2646] opened 2017-06-25 11:35 UTC
1. launch scope
2. launch chrome and point at scope
3. reset the local view state (just to ensure consistency of test conditions)
4. go to the process view, which should show something like
![screenshot from 2017-06-25 11-55-04](https://user-images.githubusercontent.com/109109/27515721-31f3c954-59a2-11e7-9d61-6664def7baa7.png)
4. stop scope
5. start scope; the display will change to something like
![screenshot from 2017-06-25 11-55-53](https://user-images.githubusercontent.com/109109/27515731-77323708-59a2-11e7-8892-b178ae429fd2.png)

Notice that a) this is a mixture of old and new nodes, and b) the topology selector says 'Containers' even though what is shown is processes.

**Comment by fbarl** [comment] 2017-06-26 14:23
Thanks the for clear instructions on how to reproduce this one @rade - I was noticing a similar behaviour before but never figured there was such a simple pattern to it!

The two issues you mentioned are indeed separate although they share the cause:

1. *Topology selector shows wrong info* - I thought this one would have been solved by modifying the line `127` in https://github.com/weaveworks/scope/pull/2600/files#diff-5897bc396ca616224f48758015a6ece1, but it might be that there is still some issues with it or that the scope version that you were using locally was taken before that commit.
2. *The nodes are merged wrongly* - here we should probably implement a mechanism that clears up the nodes after the probe reconnects and/or have smarter nodes delta merging.

Now we know how to reproduce the issue, I'll try to solve it one of the following days :)

**Comment by rade** [comment] 2017-06-26 14:34
> it might be that there is still some issues with it or that the scope version that you were using locally was taken before that commit.

Hmm. I could swear my scope was up to date, but trying to reproduce the issue just now, I only see the 2nd problem.

**Comment by rndstr** [comment] 2017-07-12 12:56
1. _Topology selector shows wrong info_ – I can reproduce; this happens because upon restart, the first response for `api/topology` does not have any processes, so the nav selection moves to the first available (containers) but keeps the graph view untouched. The second response does contain processes and they start to show up. Since you couldn't repro it's probably a race condition.

**Comment by rndstr** [comment] 2017-07-12 15:07
[moved 2. to #2708]

**Closed** 2017-07-12 15:44 UTC
Labels: accuracy, bug, component/ui
