### ISSUE TITLE
Child tables disappear in Host view 

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1079] opened 2016-03-01 13:04 UTC
Child tables appear initially, but disappear within a second.

<img width="1280" alt="host-child-tables-gone" src="https://cloud.githubusercontent.com/assets/303151/13427767/1ac7ed88-dfae-11e5-82b2-9569046e63f9.png">

Seems to only happen in an environment where Kubernetes is present - I can't replicate it with other apps.

(Scope 0.13, browser Chrome)

**Comment by davkal** [comment] 2016-03-01 15:35
@pidster got a report? I cant reproduce.

**Comment by 2opremio** [comment] 2016-03-02 05:32
Dupe of #1064 . @davkal there's a report and video there.

**Closed by 2opremio** 2016-03-02 05:32 UTC
Labels: bug, ui
