### ISSUE TITLE
Nodes appear and disappear intermittently

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#897] opened 2016-02-01 20:31 UTC
While testing #889 (b103f93) with the [ECS demo](http://www.weave.works/guides/service-discovery-and-load-balancing-with-weave-on-amazon-ecs-2/), after letting it run for a few hours I see containers appearing a disappearing intermittently.

There are 3 httpserver containers and 3 dataproducer containers which should appear at the same time in the UI but they come and go erratically:

![](http://g.recordit.co/yMt2SDF59I.gif)

Here's the report, although I am not sure it will help here: https://gist.github.com/2opremio/b3b4f435b568fb836306

I don't see a particularly high CPU or memory consumption but the UI is sloppy and loading the topologies takes a considerable time when loading the UI.

The ECS demo uses very small AWS instances (t2.micro) but Scope works just fine after it's freshly spawned.

**Comment by 2opremio** [comment] 2016-02-01 20:33
Related: #869 #827 (and maybe #854)

**Comment by paulbellamy** [comment] 2016-04-15 13:26
Possibly the probes on different nodes are being slow and missing their deadlines.

**Comment by tomwilkie** [comment] 2016-04-15 15:04
Paul can't reproduce.

**Comment by tomwilkie** [comment] 2016-04-19 15:25
@2opremio please try and reproduce.

**Comment by 2opremio** [comment] 2016-04-25 16:30
I can reproduce.

> Possibly the probes on different hosts are being slow and missing their deadlines.

I think @paulbellamy is right.

Looking at the logs I find a lot of:

```
<probe> WARN: 2016/04/25 16:25:22.817941 Topology tagger took longer than 1s
<probe> WARN: 2016/04/25 16:25:37.092299 Endpoint reporter took longer than 1s
<probe> WARN: 2016/04/25 16:25:38.651785 Docker reporter took longer than 1s
<probe> WARN: 2016/04/25 16:25:42.024260 Topology tagger took longer than 1s
<probe> WARN: 2016/04/25 16:25:55.008294 Endpoint reporter took longer than 1s
<probe> WARN: 2016/04/25 16:25:58.244352 Topology tagger took longer than 1s
<probe> WARN: 2016/04/25 16:26:11.398667 Endpoint reporter took longer than 1s
<probe> WARN: 2016/04/25 16:21:15.602084 docker container: dropping stats.
<app> ERRO: 2016/04/25 16:21:16.178981 Error on websocket: websocket: close 1006 (abnormal closure): unexpected EOF
```

Full logs: [logs.txt.gz](https://github.com/weaveworks/scope/files/234948/logs.txt.gz)

It seems that the AWS micro instances used for the demo are not powerful enoug for Scope. They used to work fine, so there must have been a performance degradation.

**Comment by 2opremio** [comment] 2016-04-25 17:41
Yep, the CPU consumption of the probe/app is pretty high considering the small amount of containers and that there are only 3 hosts:

<img width="908" alt="screen shot 2016-04-25 at 5 36 11 pm" src="https://cloud.githubusercontent.com/assets/2362916/14791163/7bb34b4a-0b0c-11e6-8fcc-fd0c6ada20d6.png">


Probe profile: [pprof.localhost:4041.samples.cpu.002.pb.gz](https://github.com/weaveworks/scope/files/235032/pprof.localhost.4041.samples.cpu.002.pb.gz)

![probe](https://cloud.githubusercontent.com/assets/2362916/14792387/e3936bbe-0b11-11e6-9725-07524f0ed179.png)

App profile: [pprof.localhost:4040.samples.cpu.001.pb.gz](https://github.com/weaveworks/scope/files/235051/pprof.localhost.4040.samples.cpu.001.pb.gz)

![app](https://cloud.githubusercontent.com/assets/2362916/14793055/27c9ce56-0b15-11e6-8fdc-f73ea7b48db1.png)

The garbage collector is dominating the CPU consumption.

Related: #1010

**Comment by 2opremio** [comment] 2016-04-25 17:45
So, the solution here is to:

* Improve performance
* Maybe use larger instances for the ECS demos (I would like to avoid this if possible since larger instances are not covered by the free tier)
* Notify users in the UI when probes are not meeting their deadlines. I have created https://github.com/weaveworks/scope/issues/1379

**Comment by tomwilkie** [comment] 2016-05-05 09:41
I think #1418 should help a lot towards CPU usage of the app.  We could probably close this one.

**Comment by tomwilkie** [comment] 2016-05-05 10:22
#1418 is in, so I think we can close this.

**Comment by 2opremio** [comment] 2016-05-13 11:08
Reopening since it still happens with the 0.15 candidate:

All the probes are dropping reports:

```
[ec2-user@ip-172-31-0-6 ~]$ docker logs --since="5m"  weavescope |& grep Dropping | tail -n 20 && date
<probe> ERRO: 2016/05/13 10:45:36.602905 Dropping report to 10.32.0.2:4040
<probe> ERRO: 2016/05/13 10:45:36.602948 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:45:41.777678 Dropping report to 127.0.0.1:4040
<probe> ERRO: 2016/05/13 10:45:46.752431 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:45:50.243380 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:45:50.243410 Dropping report to 127.0.0.1:4040
<probe> ERRO: 2016/05/13 10:45:54.513633 Dropping report to 127.0.0.1:4040
<probe> ERRO: 2016/05/13 10:45:59.237180 Dropping report to 10.32.0.2:4040
<probe> ERRO: 2016/05/13 10:45:59.237238 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:46:01.406421 Dropping report to 127.0.0.1:4040
<probe> ERRO: 2016/05/13 10:46:01.406500 Dropping report to 10.32.0.2:4040
<probe> ERRO: 2016/05/13 10:46:01.406560 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:46:06.290269 Dropping report to 127.0.0.1:4040
<probe> ERRO: 2016/05/13 10:46:06.290325 Dropping report to 10.32.0.2:4040
<probe> ERRO: 2016/05/13 10:46:06.290377 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:46:09.527878 Dropping report to 127.0.0.1:4040
<probe> ERRO: 2016/05/13 10:46:09.527907 Dropping report to 10.32.0.2:4040
<probe> ERRO: 2016/05/13 10:46:13.921125 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:46:18.355134 Dropping report to 10.36.0.2:4040
<probe> ERRO: 2016/05/13 10:46:18.355182 Dropping report to 127.0.0.1:4040
Fri May 13 10:46:22 UTC 2016
```

The apps are consuming ~40% CPU in two of the nodes just like it did at the begining of this issue.

<img width="1428" alt="screen shot 2016-05-13 at 11 47 53 am" src="https://cloud.githubusercontent.com/assets/2362916/15245915/59e7c54c-1901-11e6-9cb1-f2b99a85c405.png">


Which means that https://github.com/weaveworks/scope/pull/1418 doesn't seem to be helping.


Profile: [pprof.localhost:4040.samples.cpu.001.pb.gz](https://github.com/weaveworks/scope/files/263069/pprof.localhost.4040.samples.cpu.001.pb.gz)

![app_cpu](https://cloud.githubusercontent.com/assets/2362916/15246269/5e09b9bc-1903-11e6-85bf-538721448403.png)

**Comment by 2opremio** [comment] 2016-05-13 11:28
Related #1457

**Comment by 2opremio** [comment] 2016-08-02 10:03
This may already be fixed after the recent CPU-consumption improvements.

**Comment by rade** [comment] 2017-04-13 22:25
Let's close this; I don't see anything in this issue that points to causes other than cpu usage, which is already covered by numerous issues.

**Closed by rade** 2017-04-13 22:25 UTC
Labels: accuracy, bug, performance
