### ISSUE TITLE
labels overlap with nodes

### ISSUE THREAD

**Issue by mindfulmonk** [weaveworks/scope#1760] opened 2016-08-05 08:19 UTC
Hi All,

When running more than 50 containers the graph view becomes quite unusable. The container names start overlapping and the connections between containers are hard to see.

Here is an example:
![scope_err_too_many](https://cloud.githubusercontent.com/assets/602167/17430633/33cb779a-5aed-11e6-8dea-97fc60e224e8.png)

Possible solutions to this would be the ability to tweak the fonts/icon sizes or have something more like http://gource.io/ for the graph view.

**Comment by rade** [comment] 2016-08-05 09:44
The current graph view struggles with high node/edge counts. See #1092 and #1614. That was actually one motivation for developing the table mode. For now  that is your best option.

I am not seeing the overlap in my scopes. What browser is this? And would you mind attaching the report ("</>" in bottom right)?

**Comment by rade** [comment] 2016-08-05 10:06
I reckon this is related to #1692.

**Comment by rade** [comment] 2016-08-05 12:23
#1701 is also possibly related.

**Comment by rade** [comment] 2016-08-16 20:36
@foot @davkal I know in #1773 you said that it didn't fix this issue, but have you actually been able to reproduce the above problem since then?

**Comment by foot** [comment] 2016-08-17 07:57
proud-wind w/ both app and sys containers + browser size: 1440x800 gives something similar.

There is a bit of quick fix here in allowing the fontsize to become smaller. It looks tidier but you can't read them anymore as they're too small. Then you zoom in I guess..

**Comment by rade** [comment] 2016-08-17 08:59
> There is a bit of quick fix here in allowing the fontsize to become smaller.

Sounds reasonable. @davkal what do you think?

**Comment by davkal** [comment] 2016-08-17 09:14
Longterm we should go for semantic zoom (with nodes spacing dynamically, and hiding sub labels when zoomed out, and all labels when a complete overview fills the screen). 

This particular screenshot shows overlap in the non-connected nodes group, this is a separate layout engine, maybe we can tweak the spacing for that (wont solve this issue for 100 nodes though, need the longterm fix for that). We should not make labels unreadable, rather hide them. If they're hidden, they cant overlap :)

**Comment by rade** [comment] 2016-08-17 09:17
@foot proposed the unreadable labels as a *quick fix*. And it *is* better than overlapping labels.

Are any of the proposed alternatives just as quick to implement?

**Comment by davkal** [comment] 2016-08-17 09:19
> Are any of the proposed alternatives just as quick to implement?

Yes: node spacing for unconnected nodes.

**Comment by rade** [comment] 2016-08-17 09:27
> Yes: node spacing for unconnected nodes.

The overlap happens for others too. As you will see if you follow @foot's instructions of "proud-wind w/ both app and sys containers + browser size: 1440x800 gives something similar."

**Comment by rade** [comment] 2016-08-17 09:28
> We should not make labels unreadable, rather hide them. If they're hidden, they cant overlap :)

Can *that* be done quickly?

**Comment by davkal** [comment] 2016-08-17 09:30
> We should not make labels unreadable, rather hide them. If they're hidden, they cant overlap :)

More than an hour, less than a day.

**Comment by rade** [comment] 2016-08-17 09:32
Whereas "unreadable labels" is <1h?

**Comment by davkal** [comment] 2016-08-17 09:33
> Whereas "unreadable labels" is <1h?

Correct.

**Comment by rade** [comment] 2016-08-17 09:34
IMO that is worth doing then. And file a follow-up chore do to something better.

**Comment by 2opremio** [comment] 2016-08-17 11:08
@davkal @foot I have tentatively moved this to the 0.17.1 milestone. If you plan to fix this today, please create the PR against branch `release-0.17` instead of `master`.

**Comment by 2opremio** [comment] 2016-08-18 17:14
Fixed via #1812

**Closed by 2opremio** 2016-08-18 17:14 UTC
Labels: bug, component/ui
