### ISSUE TITLE
default view fails to select 'application containers only'

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#2120] opened 2017-01-10 22:43 UTC
Steps to reproduce:
1. run some docker container, e.g. `docker run -d -ti alpine /bin/sh`
2. fire up a scope
3. open a *private* browsing window and nagivate to localhost:4040

Expected result:
- scope select the default view & selection, which is the container view showing application containers only, and as a result only the single started container is shown
![screenshot_2017-01-10_22-33-24](https://cloud.githubusercontent.com/assets/109109/21828010/14089aa8-d786-11e6-9afb-4484b5c3a14b.png)

Actual result:
- scope shows the container view but with app/system container selection *blank*, as a result of which it shows *all* containers, i.e. the single container we launched plus the scope container.
![screenshot_2017-01-10_22-32-02](https://cloud.githubusercontent.com/assets/109109/21828014/199c9b54-d786-11e6-9d97-e2c70031dfb9.png)

This works as intended in Scope 1.0.0 and is broken in Scope 1.1.0 onwards.

**Comment by rade** [comment] 2017-01-10 22:45
I've added this to the current m/s since it rather badly affects the initial user experience.

**Comment by jpellizzari** [comment] 2017-01-12 18:40
Root cause appears to be that a topologies key was changed from "application" to "notsystem" in this commit:

https://github.com/weaveworks/scope/commit/9833a854b1638d8bd3270323c8aa0041016ebb98#diff-6126bda540b57df79f551488091760daR56

**Comment by jpellizzari** [comment] 2017-01-24 00:34
Merged PR. Closing.

**Closed by jpellizzari** 2017-01-24 00:34 UTC
Labels: bug
