### ISSUE TITLE
probe crashes immediately on Darwin

### ISSUE THREAD

**Issue by peterbourgon** [weaveworks/scope#696] opened 2015-11-25 09:34 UTC
```
$ cd probe
$ go build
$ ./probe
ugh ~/src/github.com/weaveworks/scope/probe (master …1) ./probe
<probe> 2015/11/25 10:34:21 warning: -process=true, but that requires root to find everything
<probe> 2015/11/25 10:34:21 probe starting, version dev, ID ugh
<probe> 2015/11/25 10:34:21 publishing to: localhost:4040, scope.weave.local:4040

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0xc5fc7]

goroutine 28 [running]:
github.com/weaveworks/scope/probe/endpoint.NATMapper.ApplyNAT(0x0, 0x0, 0xc820270030, 0xc820270060, 0xc820270090, 0xc8202700c0, 0xc820270150, 0xc820270180, 0xc8202700f0, 0xc820270120, ...)
        /Users/peter/src/github.com/weaveworks/scope/probe/endpoint/nat.go:70 +0xc7
github.com/weaveworks/scope/probe/endpoint.(*Reporter).Report(0xc820163540, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/peter/src/github.com/weaveworks/scope/probe/endpoint/reporter.go:143 +0xb23
main.doReport.func1(0xc82022c840, 0x1d65c40, 0xc820163540)
        /Users/peter/src/github.com/weaveworks/scope/probe/main.go:238 +0x4e
created by main.doReport
        /Users/peter/src/github.com/weaveworks/scope/probe/main.go:244 +0x119
```

**Comment by tomwilkie** [comment] 2015-11-25 10:05
The probe is now at prog/probe/scope-probe. I suspect your running an old
version, before this was fixed. I don't even think there is a main in
probe/ anymore.

**Comment by tomwilkie** [comment] 2015-11-30 08:38
Can confirm this doesn't happen on my Mac:

```
Toms-MacBook-Pro:scope twilkie$ cd prog/probe
Toms-MacBook-Pro:probe twilkie$ go build
Toms-MacBook-Pro:probe twilkie$ ./probe 
<probe> 2015/11/30 08:37:33 warning: -process=true, but that requires root to find everything
<probe> 2015/11/30 08:37:33 probe starting, version dev, ID 29d540c0877e9588
<probe> 2015/11/30 08:37:33 publishing to: localhost:4040, scope.weave.local:4040
<probe> 2015/11/30 08:37:33 Not using conntrack: module not present
<probe> 2015/11/30 08:37:33 Not using conntrack: module not present
<probe> 2015/11/30 08:37:38 multi-publisher set: localhost:4040 (127.0.0.1:4040): Get http://127.0.0.1:4040/api: dial tcp 127.0.0.1:4040: connection refused
<probe> 2015/11/30 08:37:38 Error fetching app details: Get http://127.0.0.1:4040/api: dial tcp 127.0.0.1:4040: connection refused
<probe> 2015/11/30 08:37:38 Error doing controls for 127.0.0.1:4040, backing off 1s: dial tcp 127.0.0.1:4040: connection refused
<probe> 2015/11/30 08:37:39 Error doing controls for 127.0.0.1:4040, backing off 2s: dial tcp 127.0.0.1:4040: connection refused
<probe> 2015/11/30 08:37:41 Error doing controls for 127.0.0.1:4040, backing off 4s: dial tcp 127.0.0.1:4040: connection refused
<probe> 2015/11/30 08:37:45 Error doing controls for 127.0.0.1:4040, backing off 8s: dial tcp 127.0.0.1:4040: connection refused
^C<probe> 2015/11/30 08:37:46 interrupt
<probe> 2015/11/30 08:37:46 probe exiting
Toms-MacBook-Pro:probe twilkie$ 
```

**Comment by tomwilkie** [comment] 2015-11-30 08:39
I believe this is a dupe of #589

**Closed by tomwilkie** 2015-11-30 08:39 UTC
Labels: bug
