### ISSUE TITLE
CPU/Memory usage stats do not agree with the children

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#958] opened 2016-02-12 13:25 UTC
I expect the cpu/memory usage of a node to equal the sum of the cpu/memory of it's children. The two never seem to agree, which makes me distrust the metrics.

<img width="437" alt="screen shot 2016-02-12 at 13 23 52" src="https://cloud.githubusercontent.com/assets/250199/13008048/01f45dc6-d18c-11e5-8ed8-74e982022ec1.png">

**Comment by tomwilkie** [comment] 2016-03-17 14:35
Dupe of #922

**Closed by tomwilkie** 2016-03-17 14:35 UTC
Labels: bug
