### ISSUE TITLE
Migrate to CircleCI 2.0 before August 31st

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#3303] opened 2018-08-07 12:41 UTC
CircleCI 1.0 will be decommissioned on August 31st so we should make sure to migrate the configuration to 2.0 before that happens.

**Comment by 2opremio** [comment] 2018-08-07 12:41
More dtails: https://circleci.com/blog/sunsetting-1-0/

**Comment by bboreham** [comment] 2018-08-07 12:44
Duplicate of #3288

**Closed by bboreham** 2018-08-07 12:44 UTC
Labels: chore, component/build

**Comment by 2opremio** [comment] 2018-08-07 12:56
ops, my bad
