### ISSUE TITLE
Links in details panel header are confusing

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1437] opened 2016-05-05 17:14 UTC
<img width="1326" alt="screen shot 2016-05-04 at 6 07 11 pm" src="https://cloud.githubusercontent.com/assets/2362916/15022379/46debe18-1223-11e6-86f2-fba91b04d190.png">

In the example above there are three`gke-fons..` `frontend..` `nginx` but the identifiers alone don't tell you where the links will land you.

A tag or even better, an icon, next to the identifiers would be very helpful

**Comment by tomwilkie** [comment] 2016-05-05 17:19
Dupe of #921

**Closed by tomwilkie** 2016-05-05 17:19 UTC
Labels: ui

**Comment by 2opremio** [comment] 2016-05-05 17:20
ops, sorry, hadn't seen that one

**Comment by tomwilkie** [comment] 2016-05-05 17:21
No worries, thats what I'm here for :-)!
