### ISSUE TITLE
Improve plugin documentation

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1645] opened 2016-07-05 13:51 UTC
We should, improve the plugin docs, including:
- the api datastructures
- the things plugins are allowed to do, and can't do

**Comment by rade** [comment] 2017-01-10 23:28
#1963 got opened as a duplicate of this. Alas since we are only discovering this now, it has way more info than this issue, so I am closing this one as a dup.

**Closed by rade** 2017-01-10 23:28 UTC
Labels: chore, component/docs
