### ISSUE TITLE
Scope probes cause Docker engine to become unresponsive in DC/OS

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#2479] opened 2017-04-27 11:46 UTC
(A report from a user to me.)
 
On DC/OS 1.8, with ~15 hosts and Scope configured with probes pointing to a single Scope web app.

Shortly after probes are started, they cause[1] the Docker engine on each host to become unresponsive and DC/OS is unable to schedule other tasks. 

A log snipped showing some errors was provided - but the description of the problem is the main issue.

    I0426 21:40:44.577608 24433 exec.cpp:161] Version: 1.0.3
    I0426 21:40:44.583099 24440 exec.cpp:236] Executor registered on agent XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    I0426 21:40:44.584244 24436 docker.cpp:815] Running docker -H unix:///var/run/docker.sock run --privileged --cpu-shares 51 --memory 268435456 -e MARATHON_APP_LABEL_DCOS_PACKAGE_SOURCE=https://universe.mesosphere.com/repo -e MARATHON_APP_VERSION=2017-04-26T20:40:38.358Z -e HOST=172.N.N.N -e MARATHON_APP_RESOURCE_CPUS=0.05 -e MARATHON_APP_LABEL_DCOS_PACKAGE_REGISTRY_VERSION=2.0 -e PORT_10132=16093 -e MARATHON_APP_RESOURCE_GPUS=0 -e MARATHON_APP_LABEL_DCOS_PACKAGE_RELEASE=1 -e MARATHON_APP_DOCKER_IMAGE=weaveworks/scope:1.3.0 -e MARATHON_APP_LABEL_DCOS_PACKAGE_NAME=weavescope-probe -e MARATHON_APP_LABEL_DCOS_PACKAGE_VERSION=0.15.0 -e MESOS_TASK_ID=ops_weavescope-probe.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -e PORT=16093 -e MARATHON_APP_RESOURCE_MEM=256.0 -e PORTS=16093 -e MARATHON_APP_LABEL_DCOS_PACKAGE_IS_FRAMEWORK=false -e MARATHON_APP_RESOURCE_DISK=0.0 -e MARATHON_APP_LABELS=DCOS_PACKAGE_RELEASE DCOS_PACKAGE_SOURCE DCOS_PACKAGE_REGISTRY_VERSION DCOS_PACKAGE_VERSION DCOS_PACKAGE_NAME DCOS_PACKAGE_IS_FRAMEWORK -e MARATHON_APP_ID=/ops/weavescope-probe -e PORT0=16093 -e LIBPROCESS_IP=172.N.N.N -e MESOS_SANDBOX=/mnt/mesos/sandbox -e MESOS_CONTAINER_NAME=mesos-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -v /var/run/docker.sock:/var/run/docker.sock:rw -v /var/lib/mesos/slave/slaves/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/frameworks/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/executors/ops_weavescope-probe.9b4ea839-2ac0-11e7-a829-e6f9e9345cc9/runs/XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:/mnt/mesos/sandbox --net host --pid=host --name mesos-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX weaveworks/scope:1.3.0 --no-app --probe.docker=true --probe.no-controls=true weavescope.ops.marathon.mesos
    time="2017-04-26T20:40:45Z" level=info msg="publishing to: weavescope.ops.marathon.mesos" 
    <probe> INFO: 2017/04/26 20:40:45.400565 command line args: --logtostderr=true --mode=probe --no-app=true --probe.docker=true --probe.no-controls=true weavescope.ops.marathon.mesos
    <probe> INFO: 2017/04/26 20:40:45.400622 probe starting, version 1.3.0, ID 11510700fefe7ea8
    <probe> ERRO: 2017/04/26 20:40:45.430113 plugins: problem loading: no such file or directory
    <probe> WARN: 2017/04/26 20:40:45.432900 Error collecting weave status, backing off 10s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
    <probe> WARN: 2017/04/26 20:40:45.433307 Cannot resolve 'scope.weave.local.': dial tcp 172.17.0.1:53: getsockopt: connection refused
    <probe> INFO: 2017/04/26 20:40:45.434411 Success collecting weave proxy status
    <probe> INFO: 2017/04/26 20:40:45.434485 Success collecting weave plugin status
    <probe> ERRO: 2017/04/26 20:40:45.446742 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
    <probe> ERRO: 2017/04/26 20:40:45.454601 conntrack stderr:NOTICE: Netlink socket buffer size has been set to 425984 bytes.
    <probe> WARN: 2017/04/26 20:40:45.496833 Error collecting weave ps, backing off 20s: exit status 1: "Link not found\n"
    <probe> INFO: 2017/04/26 20:40:48.542788 Publish loop for weavescope.ops.marathon.mesos starting
    <probe> WARN: 2017/04/26 20:40:55.433557 Error collecting weave status, backing off 20s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
    <probe> ERRO: 2017/04/26 20:41:00.495888 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-probe?arch=amd64&flag_kernel-version=0.0.0-514.2.2.el7.x86_64&flag_os=linux&os=linux&signature=UpmQ7tnaXFbu3XuMTAtzDs8WE9ONwXrSgRDq2foSvCg%3D&version=1.3.0: dial tcp 74.125.71.121:443: i/o timeout
    <probe> WARN: 2017/04/26 20:41:05.564715 Error collecting weave ps, backing off 40s: exit status 1: "Link not found\n"
    <probe> WARN: 2017/04/26 20:41:15.436603 Error collecting weave status, backing off 40s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
    <probe> ERRO: 2017/04/26 20:41:15.622037 Error checking version: Get https://checkpoint-api.weave.works/v1/check/scope-probe?arch=amd64&flag_kernel-version=0.0.0-514.2.2.el7.x86_64&flag_os=linux&os=linux&signature=UpmQ7tnaXFbu3XuMTAtzDs8WE9ONwXrSgRDq2foSvCg%3D&version=1.3.0: dial tcp 74.125.71.121:443: i/o timeout
    <probe> WARN: 2017/04/26 20:41:45.642995 Error collecting weave ps, backing off 1m0s: exit status 1: "Link not found\n"
    <probe> WARN: 2017/04/26 20:41:55.439923 Error collecting weave status, backing off 1m0s: Get http://127.0.0.1:6784/report: dial tcp 127.0.0.1:6784: getsockopt: connection refused
    <probe> ERRO: 2017/04/26 20:44:34.477230 Error fetching app details: Get http://172.N.N.N:4040/api: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    <probe> ERRO: 2017/04/26 20:44:34.477300 Error doing publish for weavescope.ops.marathon.mesos, backing off 1s: Post http://172.23.22.54:4040/api/report: net/http: request canceled
    <probe> INFO: 2017/04/26 20:44:34.477317 Publish loop for weavescope.ops.marathon.mesos exiting
    <probe> INFO: 2017/04/26 20:44:42.556094 Publish loop for weavescope.ops.marathon.mesos starting
    <probe> ERRO: 2017/04/26 20:53:04.540274 Error fetching app details: Get http://172.N.N.N:4040/api: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    <probe> ERRO: 2017/04/26 20:53:04.540357 Error doing publish for weavescope.ops.marathon.mesos, backing off 1s: Post http://172.23.22.54:4040/api/report: net/http: request canceled
    <probe> INFO: 2017/04/26 20:53:04.540375 Publish loop for weavescope.ops.marathon.mesos exiting
    <probe> INFO: 2017/04/26 20:53:12.563233 Publish loop for weavescope.ops.marathon.mesos starting
    <probe> ERRO: 2017/04/26 21:20:34.557488 Error doing publish for weavescope.ops.marathon.mesos, backing off 1s: Post http://172.23.22.54:4040/api/report: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    <probe> ERRO: 2017/04/26 21:20:34.656543 Error fetching app details: Get http://172.N.N.N:4040/api: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
    <probe> INFO: 2017/04/26 21:20:34.656595 Publish loop for weavescope.ops.marathon.mesos exiting
    <probe> INFO: 2017/04/26 21:20:42.565760 Publish loop for weavescope.ops.marathon.mesos starting
    INFO: 2017/04/26 21:22:25.198565 === received SIGINT/SIGTERM ===
    *** exiting
    /sbin/sv stop probe: waitid: no child processes
    reaped child process 16596 (256)
    /sbin/runsvdir exited with error: waitid: no child processes

1. Convincingly proven by starting/stopping probes several times. When the probes are not running, DC/OS works fine.

**Comment by 2opremio** [comment] 2017-04-27 12:15
What's the docker version, how big are the machines?

Likely related: https://github.com/containerd/containerd/issues/757

**Comment by 2opremio** [comment] 2017-04-27 12:16
Likely dupe of https://github.com/weaveworks/scope/issues/2245

**Comment by rade** [comment] 2017-08-03 10:23
> This is likely a dupe of #2245

Let's go with that.

**Closed by rade** 2017-08-03 10:23 UTC
Labels: bug, performance
