### ISSUE TITLE
Remove the 100 node limit in the UI

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1164] opened 2016-03-12 17:30 UTC
See https://weaveworks.slack.com/archives/scope/p1457802055000002

And https://twitter.com/_dancannon/status/708698431615864832

**Comment by 2opremio** [comment] 2016-03-12 18:39
Duplicate of https://github.com/weaveworks/scope/issues/1034

**Closed** 2016-03-12 18:44 UTC
Labels: ui
