### ISSUE TITLE
Move to Circle 2.0

### ISSUE THREAD

**Issue by fbarl** [weaveworks/scope#3288] opened 2018-07-27 14:49 UTC
From any of our jobs in Circle CI:

![image](https://user-images.githubusercontent.com/1216874/43327674-4d2a32be-91bc-11e8-8877-859a87974c3e.png)

We only have about one more month to go!

Could potentially help with #2271.

**Comment by fbarl** [comment] 2018-08-07 09:58
A hint from @bboreham in https://github.com/weaveworks/scope/pull/3295#issuecomment-409531361:

> I've tended to use pre-build build images for speed. E.g. https://github.com/weaveworks/weave/pull/3270/files , https://github.com/weaveworks/service-conf/blob/master/.circleci/config.yml

**Comment by fbarl** [comment] 2018-08-07 10:05
Anyone else feels like having a stab at it? @bboreham @leth @guyfedwards

**Comment by guyfedwards** [comment] 2018-08-07 11:16
Happy to pick it up 👍

**Comment by guyfedwards** [comment] 2018-08-20 10:48
I don't think I am going to have much time this week to look at this, anyone else has some time, @bboreham @leth ?

**Comment by bboreham** [comment] 2018-08-25 10:07
Duplicate of #3217

**Closed by bboreham** 2018-08-25 10:07 UTC
Labels: chore, component/build
