### ISSUE TITLE
Consider imposing memory limits on scope

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#811] opened 2016-01-12 20:59 UTC
We've had a few reports of weird behaviors (lots of conntracks but no trace in the scope logs, scope reparenting to init and docker not thinking its running) that we think might be down to the behaviour of the OOM killer and a potential memory leak / bug in Scope.

Perhaps we should consider using the [memory limiting features of docker](https://docs.docker.com/engine/reference/run/#user-memory-constraints) to impose limits on scope's memory usage, the theory being that scope will be the one that dies if it hits problems, and won't cause other things (like docker) to be OOM killed.

@2opremio thoughts?

**Comment by 2opremio** [comment] 2016-01-12 23:00
> might be down to the behaviour of the OOM killer

Interesting. If I recall properly what I observed was, this process tree


```
              `runsysv` 
              /            \
        `runsysv`  `runsysv` 
              |             |
scope-probe     scope-app
```

and a lot of conntrack processes pending from the hosts' init without an associated running container (`docker ps -a` showed a `weavescope` containers which exited a few weeks ago)

I am not fully familiar with Linux' OOM killer, but in order for `runsysv` to be orphaned and picked up by the host's init, the OOM-killer would have had to kill the docker parent, which strikes me as extremely odd.

On the other hand, it can explain the conntrack processes pending from init: the scope probe gets killed because of the high memory consumption and its conntrack children.

So it could be a combination of the OOM-killer killing the Scope Probe process and Docker not handling these situations gracefully (maybe because because of --pid=host) but I don't don't see how can this happen without a Docker bug (or perhaps a kernel bug, but that would be a long shot).

> Perhaps we should consider using the memory limiting features of docker to impose limits on scope's memory usage

The problem is ... what limit? Isn't the probe's consumption proportional to the what happens in the host? (e.g. number of processes).

**Comment by rade** [comment] 2017-04-14 02:17
I can't see us coming up with sensible limits that work for everyone and are actually useful. Users can set their own limits via WEAVESCOPE_DOCKER_ARGS.

-> closing.

**Closed by rade** 2017-04-14 02:17 UTC
Labels: chore
