### ISSUE TITLE
Some container nodes are not displayed all the time

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1051] opened 2016-02-26 16:17 UTC
<img width="1197" alt="screenshot 2016-02-26 16 16 21" src="https://cloud.githubusercontent.com/assets/251467/13357872/6bf06530-dca4-11e5-9cbf-ad1b906a402d.png">
<img width="1361" alt="screenshot 2016-02-26 16 16 46" src="https://cloud.githubusercontent.com/assets/251467/13357870/6bec6840-dca4-11e5-9a15-f7f5fd1a9b11.png">
<img width="1394" alt="screenshot 2016-02-26 16 16 55" src="https://cloud.githubusercontent.com/assets/251467/13357871/6bef34f8-dca4-11e5-95b1-5ba25f512b56.png">

[***Report***](https://gist.github.com/errordeveloper/b3e45fa2ea00777898ac)

**Comment by 2opremio** [comment] 2016-02-27 12:26
What view is this? The container view?

**Comment by tomwilkie** [comment] 2016-04-19 15:15
This is a dupe of #1130

**Closed by tomwilkie** 2016-04-19 15:15 UTC
