### ISSUE TITLE
Doing a force re-layout resets zoom level

### ISSUE THREAD

**Issue by jpellizzari** [weaveworks/scope#2377] opened 2017-03-22 21:34 UTC
Reproduce:

1. Zoom in on a topology
2. Re-layout button (bottom right toolbar)

Expected:
Re-layout happens

Actual:
Re-layout happens but zoom level is reset.

**Comment by fbarl** [comment] 2017-03-24 14:28
It's a feature, not a bug :) When I was refactoring the zooming logic, I decided that resetting the zoom state would be a desirable action when forcing relayouting - I do it explicitly in `CLICK_FORCE_RELAYOUT` action in `root.js`.

The reasoning was that that button is normally clicked either when there is something wrong with the layout or the nodes' layout is obviously non-optimal - in both cases, we might expect radical repositioning of nodes & edges so staying zoomed in somewhere on a big graph, we'd by all chance lose the context anyway (or at least that was my experience before I started doing these resets).

Should we ask other people what they think?

Ideally, we'd want to make that button less and less relevant though, but I think that's still a long way ahead. :)

**Comment by jpellizzari** [comment] 2017-03-24 15:04
This was brought up by @ekimekim in Slack.

My vote is to always have the layout re-organize automatically. I thought the "dancing nodes" was preferable, as the motion indicated something was changing.

**Comment by rade** [comment] 2017-03-24 15:20
No, dancing nodes is not preferable.

**Comment by fbarl** [comment] 2017-03-24 16:01
I think the problem was that the nodes would "dance" around too much if we'd let the layout engine re-run on every update from backend. So we're re-organizing the layout only if the change to the nodes is *significant*, gaining some graph stability that way. I guess that code there in `nodes-layout.js` is not bullet-proof, so sometimes the layout breaks.

Letting the nodes dance too much might be really chaotic on higher zooms in big graphs, so my vote is to not change that logic too much unless there are some strong pros (or layouting bug fixes) :)

**Comment by ekimekim** [comment] 2017-03-25 07:50
My most common reason for pressing the update button is that a new container has become connected, and I want to see it in its proper place instead of way off to the side in the pile of unconnected containers. I find that a layout update does not often drastically change what I'm looking at.

The new behaviour means I lose what I'm looking at entirely every time I press refresh, since the default zoom includes all nodes including unconnected ones, not just the part I'm interested in. This is especially bad if nodes are becoming disconnected and connected rapidly, so I'm pressing the button every few seconds.

I would prefer dancing nodes.

**Comment by rade** [comment] 2017-03-25 14:42
Why can't we have the original behaviour back? Nobody was complaining.

> I would prefer dancing nodes.

Believe me, you don't.

**Comment by fbarl** [comment] 2017-03-28 10:09
> Why can't we have the original behaviour back? Nobody was complaining.

Original behaviour being not resetting the zoom when refreshing the layout? If yes, then I could easily remove those couple of lines of code that nobody seems to like :(

**Comment by rade** [comment] 2017-04-07 13:18
I am still (or again?) seeing this in both dev and prod. It's very, very, annoying!

**Comment by fbarl** [comment] 2017-04-07 14:06
@rade So this issue was fixed 10 days ago, but it never made it to neither `dev` nor `prod` because now we need to manually update scope reference in `service-ui/package.json` every time we make changes to its UI and nobody did it since this fix was merged.

**Closed** 2017-04-07 15:09 UTC
Labels: bug, component/ui
