### ISSUE TITLE
Opening a pipe fails on first attempt

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1095] opened 2016-03-02 15:42 UTC
<img width="1273" alt="screenshot 2016-03-02 15 41 30" src="https://cloud.githubusercontent.com/assets/251467/13465400/6038599a-e08d-11e5-8c44-dd3bf072cc72.png">
<img width="948" alt="screenshot 2016-03-02 15 42 00" src="https://cloud.githubusercontent.com/assets/251467/13465401/603a7aae-e08d-11e5-8948-f3ff5410a19c.png">

**Comment by errordeveloper** [comment] 2016-03-02 15:43
@tomwilkie said it's by design, but should be 404 instead of 400...

**Comment by foot** [comment] 2016-03-02 16:11
It is by design :).

`404`: pipe doesn't exist, request a new one.
`400`: pipe exists! why are you connecting to a websocket endpoint w/ a xhr GET? that is a very invalid thing to do here is a 400 for your troubles.

So we might be able to "fix" this in the client by checking if a pipe exists w/ a WS connection instead, I forget if we tried to do that in the past and it didn't work for some reason... Or the server could add a new endpoint that is not a WS that returns a 200 if a pipe exists.

**Comment by foot** [comment] 2016-03-02 16:12
I will try in the client first.

**Comment by foot** [comment] 2016-03-02 16:59
Oh yeah you can't read the http response code from a WS for browser security reasons.

Earlier discussions https://github.com/weaveworks/scope/pull/650#discussion_r47257963

We'd need a new server endpoint.

**Comment by tomwilkie** [comment] 2016-03-03 09:17
Dupe of #994

**Closed by tomwilkie** 2016-03-03 09:17 UTC
