### ISSUE TITLE
Ubuntu 15.10 on GCE: Weave container has no IP address

### ISSUE THREAD

**Issue by faddat** [weaveworks/scope#586] opened 2015-10-23 19:27 UTC
![snapshot1](https://cloud.githubusercontent.com/assets/7142025/10702856/61bf2832-79f6-11e5-9e34-d951b5db18db.png)

Two ubuntu 15.10 hosts, same issue.  Tried having a clien connect to master, same deal no luck.  Happy to help troubleshoot.  

Steps:
Create fresh 15.10 instance on GCE
Install Docker
Install Weave
Start Weave
Install Scope
Start Scope

**Comment by tomwilkie** [comment] 2015-10-23 20:07
Hi Jacob; thanks for the report. This is caused by the new weave 1.2
release and it's fast data path. It's already fixed in scope master, and we
aim to do a release first thing on Monday.

If you'd like to test, you could use the scope script from master, which
will download a recent build with the fix in.

Thanks

Tom

**Comment by tomwilkie** [comment] 2015-10-23 20:27
Here is the original issue (#586) and PR (#574)

**Closed** 2015-10-24 09:22 UTC
