### ISSUE TITLE
Errors with Docker Swarm

### ISSUE THREAD

**Issue by ronny35** [weaveworks/scope#2178] opened 2017-02-01 17:21 UTC
Scope project does not permit to display all networks in case of Swarm mode enabled.

**Comment by 2opremio** [comment] 2017-02-02 11:25
@ronny35 Can you elaborate? What were you expecting to see? What errors are you getting?

**Comment by ronny35** [comment] 2017-02-02 12:34
I use docker in Swarm Mode and, using Weave Scope, I would like to obtain graphical state of my cluster when I deploy a new service in specific network.
Today, I have only some containers of this new service (in case of running in single node) and I have not link between containers in the same network.

**Comment by 2opremio** [comment] 2017-02-02 12:45
@ronny35 Can you share a screenshot and explain what you were expecting to see?

Are there any tcp connections between the containers for which you expect and edge? Edges represent actual connections happening between them not a network-belonging relationship.

**Comment by ronny35** [comment] 2017-02-02 14:53
![screen](https://cloud.githubusercontent.com/assets/15168987/22553901/97b2f99a-e95e-11e6-9564-77d22d768344.jpg)

It means if one container A (backend) need to connect to container B (database), the edge must be present in UI Scope ?

**Comment by 2opremio** [comment] 2017-02-02 14:56
Is there an existing TCP connection between those two containers? Did you get a confirmation by other means? (e.g.. netstat)

**Comment by 2opremio** [comment] 2017-02-02 14:56
Again, there must be a TCP connections between the containers for Scope to show an edge.

**Comment by 2opremio** [comment] 2017-02-02 14:57
What's more, the connection needs to be TCPv4 (we don't track TCPv6 connections yet).

**Comment by ronny35** [comment] 2017-02-03 11:37
I have deployed two services with tcp connections between us (inside the same network) and edges are not present.

**Comment by 2opremio** [comment] 2017-02-03 11:57
Alright. I am going to need a way to reproduce. 

Can you get me the Scope report? (`</>` button in the bottom left corner) and the output of `netstat -tn` in each container?

Please make sure that the report doesn't contain any sensitive information before forwarding it.

**Comment by rade** [comment] 2017-07-31 07:14
Closing this due to lack of reproducibility. Please re-open when there is further info.

**Closed by rade** 2017-07-31 07:14 UTC
