### ISSUE TITLE
Popped out terminal window gets stuck

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2502] opened 2017-05-07 16:39 UTC
Browser: Chrome 57.0.2987.133 (64-bit)
Version: VERSIONc897c188 ON service

(The .JSON report is attached as a txt)

Doing a grep on the system and then popping out the terminal causes white, empty screen (frozen): 

![screen shot 2017-05-07 at 11 32 55 am](https://cloud.githubusercontent.com/assets/13420383/25782932/d8befb60-3318-11e7-9b51-4c43aa78f237.png)

Yet processes are still running looking at the CPU: 

![screen shot 2017-05-07 at 11 35 35 am](https://cloud.githubusercontent.com/assets/13420383/25782941/1593f9b4-3319-11e7-9251-2f883aa4ad0b.png)

[Grep-popping-out-window.txt](https://github.com/weaveworks/scope/files/981743/Grep-popping-out-window.txt)

**Comment by 2opremio** [comment] 2017-05-08 14:54
@abuehrle Is it reproducible? Was it a host terminal? Did you pop out the terminal while the command was running?

**Comment by abuehrle** [comment] 2017-05-08 14:55
I was running a command, but I saw the same behaviour without running a command.  I will invite you to the instance.

**Comment by abuehrle** [comment] 2017-05-08 16:57
Yes it was on a host terminal (on the Master node).

**Comment by abuehrle** [comment] 2017-05-24 17:38
This is still a problem. The terminal is not re-initializing when you pop it out and only does so when you hit return: 

http://recordit.co/wJWaXtjT3B

**Comment by 2opremio** [comment] 2017-05-24 17:44
I think that the UI should save the terminal buffer and copy it to the pop-up when detaching the window.

**Comment by abuehrle** [comment] 2017-06-22 15:44
I am also seeing this when popping out the log terminal: 

1. Chrome (Kubernetes, Sockshop, Digital Ocean, Ubuntu)
2. Searched for Scope (while filtered on Containers > System Containers >Running Containers > Show uncontained > All Namespaces

<img width="1203" alt="screen shot 2017-06-22 at 11 40 55 am" src="https://user-images.githubusercontent.com/13420383/27443092-17f70372-5740-11e7-820b-7353e26a6eec.png">

**Comment by rade** [comment] 2017-07-12 11:17
The terminal window not retaining history when popping out is #2151.

The terminal window "freezing" when popping out would be a bug. @abuehrle next time you see this in an instance, please invite me.

**Comment by abuehrle** [comment] 2017-07-12 12:48
This is still occurring when you can get messages to appear.  You are in the instance as listed above (cold-hill-34).  Now however I am seeing some other behaviour that is new. (I will log a different issue. )

**Comment by rade** [comment] 2017-07-12 12:56
> This is still occurring when you can get messages to appear.

*What* is still occurring? The frozen, white terminal window? And what do you mean by "when you can get messages to appear"?

> You are in the instance as listed above (cold-hill-34)

I've successfully popped out both terminal and log windows for a weave scope agent container. Everything seems to work as expected, modulo #2151.

**Comment by abuehrle** [comment] 2017-07-12 13:19
The terminal no longer looks frozen, but log messages do not resume when you pop out the window.  

There is also an additional problem of when you pop out the terminal and click something on the main screen, the popped out terminal is hidden beneath the browser (I'll log a separate issue for that). 

http://recordit.co/5P5LMCUk2v

**Comment by rade** [comment] 2017-07-12 13:26
> The terminal no longer looks frozen, but log messages do not resume when you pop out the window.

That is definitely a bug.

> There is also an additional problem of when you pop out the terminal and click something on the main screen, the popped out terminal is hidden beneath the browser (I'll log a separate issue for that).

That is totally expected behaviour. You've popped out the window; it's now behaves like any other window on your system.

**Comment by abuehrle** [comment] 2017-07-12 13:31
>That is totally expected behaviour. You've popped out the window; it's now behaves like any other window on your system.

Filed a new issue for this #2706

**Comment by rade** [comment] 2017-07-12 13:38
>> log messages do not resume when you pop out the window.
>
> That is definitely a bug.

I think that's a separate bug from the "white, frozen" bug described here. AFAICT it only happens for pods, so I suspect some brokenness in the pod log re-attachment logic. Can you reproduce the problem (logs showing fine while not popped out, but not resuming when popped out) for plain containers?

**Comment by abuehrle** [comment] 2017-07-12 13:47
>Can you reproduce the problem (logs showing fine while not popped out, but not resuming when popped out) for plain containers?

Plain containers seem to work fine: 

http://recordit.co/sb78X2TYa6

**Comment by abuehrle** [comment] 2017-07-12 14:39
As a follow up here I left the Kube-api window open for some time, and logs do eventually resume. I opened a new log window on the kube-api and compared the messages and both windows match and are up to date.  So this may not be an issue.

**Comment by abuehrle** [comment] 2017-07-13 05:36
freezing terminal is fixed

**Comment by abuehrle** [comment] 2017-07-13 16:52
I think this is still an issue and needs investigation. Not sure under what circumstances this fails. 

But I have captured a screen shot below that shows the Kube-api logs popped out and a view of the logs not popped out. The popped out version is still 'stuck' and doesn't resume logs (I left it open for about five minutes).  

same instance: cold-hill-34

![screen shot 2017-07-13 at 11 47 00 am](https://user-images.githubusercontent.com/13420383/28177795-a01fb366-67c1-11e7-9ce6-5c1c67978765.png)

**Comment by bboreham** [comment] 2017-07-24 12:45
When I get this issue, if I open Chrome developer tools I see this:

```
vendors.js?7c5df1b…:1 Uncaught TypeError: Cannot read property 'call' of undefined
    at n (vendors.js?7c5df1b…:1)
    at Object.<anonymous> (terminal-app-7a51cc8….js?7c5df1b…:29)
    at n (vendors.js?7c5df1b…:1)
    at Object.<anonymous> (terminal-app-7a51cc8….js?7c5df1b…:41)
    at n (vendors.js?7c5df1b…:1)
    at window.webpackJsonp (vendors.js?7c5df1b…:1)
    at terminal-app-7a51cc8….js?7c5df1b…:1
n @ vendors.js?7c5df1b…:1
(anonymous) @ terminal-app-7a51cc8….js?7c5df1b…:29
n @ vendors.js?7c5df1b…:1
(anonymous) @ terminal-app-7a51cc8….js?7c5df1b…:41
n @ vendors.js?7c5df1b…:1
window.webpackJsonp @ vendors.js?7c5df1b…:1
(anonymous) @ terminal-app-7a51cc8….js?7c5df1b…:1
```

**Comment by rade** [comment] 2017-07-26 05:21
@foot iirc you said you know what the problem was here.

**Comment by foot** [comment] 2017-07-26 09:02
Broken on prod:
 - scope@a6d3542c
 - service-ui@b7c93a3

Works on dev:
 - scope@d9705bc6
 - service-ui@3707202

**Comment by rade** [comment] 2017-07-26 09:24
The standalone scope on prod works fine for me. Which suggests that this is a service-ui issue.

**Comment by foot** [comment] 2017-07-26 15:55
Fixed by deploying prod.

Nothing in `git log d9705bc6... a6d3542c` is an obvious culprit. Maybe some of the transitional npm -> yarn work? Maybe a bad day on circle.

Please re-open this if you see it again.

Other things we could do if this happens again: Add comment header to bundle.js's w/ build details so we can inspect the build that generated them.

**Comment by rade** [comment] 2017-10-04 13:33
Bryan and I are both seeing this - blank, frozen window on pop-out - (again) consistently for host terminals in dev-on-prod but not dev-on-dev.

**Comment by foot** [comment] 2017-10-04 13:52
ta. yeah, its the scope/(index|terminal).html served up by the scope query service is broken again.

We should move terminal.html into service-ui anyway.

I'm curious as to whats happening w/ the scope build so will have a poke..

**Comment by foot** [comment] 2017-10-12 09:19
The terminal issue has been fixed by https://github.com/weaveworks/service-ui/pull/1192 and https://github.com/weaveworks/scope/pull/2882.

The scope build is still probably there, new issue #2889.

**Closed by foot** 2017-10-12 09:19 UTC
Labels: bug, component/ui
