### ISSUE TITLE
Unrelated clusters overlap

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1268] opened 2016-04-12 14:30 UTC
Two separate groups of connected nodes are rendered with a significant overlap, confusing the view.
Attached archive contains the JSON report and an SVG showing an example.

[archive.zip](https://github.com/weaveworks/scope/files/215203/archive.zip)

**Comment by davkal** [comment] 2016-04-12 15:14
Here is the SVG rendered:
![screen shot 2016-04-12 at 17 13 01](https://cloud.githubusercontent.com/assets/859729/14465086/ec5e7594-00d1-11e6-95f2-d0c4bbdb53ec.png)

@pidster could u draw your ideal diagram?

**Comment by pidster** [comment] 2016-04-13 11:13
Ideally the two groups should be distinct.
Edges from group 1 may intersect with edges from group 1, but should not intersect with edges from group 2.
In the example above, the edges from the swarm/consul group intersect with edges from the unconnected/unrelated weave/scope group. There are 4 weave nodes on the upper left that are far located far away from the rest of the connected group.

**Comment by tomwilkie** [comment] 2016-04-20 15:29
I believe this is a dupe of #361

**Closed by tomwilkie** 2016-04-20 15:29 UTC
Labels: ui
