### ISSUE TITLE
Containers incorrectly attributed to host

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1472] opened 2016-05-11 10:44 UTC
<img width="1637" alt="screen shot 2016-05-11 at 11 40 07" src="https://cloud.githubusercontent.com/assets/2362916/15178395/3748d930-176d-11e6-8dc8-f80681d11093.png">

This is kubernetes and note how a single host is attributed 3 (all) the scope probes whilst there is a one-to-one mapping between probes (DaemonSet) and hosts .

Report: [report_wrongly_attributed_containers.json.gz](https://github.com/weaveworks/scope/files/259095/report_wrongly_attributed_containers.json.gz)

**Comment by 2opremio** [comment] 2016-05-11 10:48
Once is a while very briefly (1 second) shows the correct table:

<img width="1637" alt="screen shot 2016-05-11 at 11 45 10" src="https://cloud.githubusercontent.com/assets/2362916/15178544/0ef8daec-176e-11e6-8981-1fa127916eca.png">

Possibly related: https://github.com/weaveworks/scope/issues/1064

**Comment by tomwilkie** [comment] 2016-05-11 14:23
I don't get this on gke:

![screen shot 2016-05-11 at 16 20 56](https://cloud.githubusercontent.com/assets/444037/15184213/909c4d9c-1794-11e6-93ff-7ff18174984b.png)

[report.json.zip](https://github.com/weaveworks/scope/files/259505/report.json.zip)

**Comment by tomwilkie** [comment] 2016-05-11 14:24
I suspect this is a dupe of #1081, although I don't see why fons is hitting it (it was fixed)

**Comment by 2opremio** [comment] 2016-05-11 14:34
@paulbellamy can reproduce

**Comment by paulbellamy** [comment] 2016-05-11 14:41
I *do* get this on gke..

[report.zip](https://github.com/weaveworks/scope/files/259550/report.zip)

**Comment by tomwilkie** [comment] 2016-05-11 14:42
Hmmm, weird.  Will investigate tomorrow.  Feel free to fix it before me if you want...

**Comment by paulbellamy** [comment] 2016-05-12 09:50
It's not intermittent, it just assigns a bunch of "extra" containers to one of the hosts at any given time (which moves around).

**Comment by paulbellamy** [comment] 2016-05-12 10:28
It's to do with having the ContainerImageRenderer and PodRenderer rolled up into the HostRenderer. Not sure quite how, yet...

**Comment by paulbellamy** [comment] 2016-05-12 10:34
Also, existed in 0.14.0

**Comment by paulbellamy** [comment] 2016-05-12 10:58
Ah ha. In previous versions of docker the container image id was different on each host. Now, they are the same. This means the container images have a random host_node_id based on whichever probe reported latest. Then because the children are propagated in NewDerivedNode all the containerImage's children (probes on other hosts) get set as children of the host.

**Comment by tomwilkie** [comment] 2016-05-12 11:04
> Also, existed in 0.14.0

I thought this was because every probe produced nodes for every container in the k8s reporter.

**Closed** 2016-05-12 13:50 UTC
Labels: bug, k8s
