### ISSUE TITLE
Goroutine leak in app?

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1949] opened 2016-10-25 13:06 UTC
![screen shot 2016-10-25 at 14 06 33](https://cloud.githubusercontent.com/assets/444037/19687148/450bb3f8-9abc-11e6-8ca6-bdb7b154e123.png)

**Comment by rade** [comment] 2016-10-25 13:08
dup of #1916?

**Comment by ekimekim** [comment] 2016-10-31 17:33
@tomwilkie @paulbellamy I seem to recall you saying you fixed something related to this, and I can't see this same graph in current dev. Is this fixed?

**Comment by ekimekim** [comment] 2016-10-31 17:47
instead of cross-posting everything, i'm just going to close this as a dupe of #1916

**Closed by ekimekim** 2016-10-31 17:47 UTC
Labels: bug
