### ISSUE TITLE
conntrack issues and timeouts

### ISSUE THREAD

**Issue by mindfulmonk** [weaveworks/scope#1814] opened 2016-08-17 16:07 UTC
Hello,

I have another cluster in which I'm hitting this issue:

```
<probe> WARN: 2016/08/17 16:00:53.816435 Topology tagger took longer than 1s
<probe> WARN: 2016/08/17 16:00:54.018759 Topology tagger took 1.402196131s (longer than 1s)
<probe> WARN: 2016/08/17 16:00:58.018177 background /proc reader: full pass took 19.60082242s: 50% more than expected (10s)
<probe> WARN: 2016/08/17 16:01:02.819433 Endpoint reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:03.116762 Endpoint reporter took 2.097042329s (longer than 1s)
<probe> ERRO: 2016/08/17 16:01:06.616544 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.ReplicationController: Get https://192.168.0.1:443/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> ERRO: 2016/08/17 16:01:06.616658 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Node: Get https://192.168.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> ERRO: 2016/08/17 16:01:07.016617 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Pod: Get https://192.168.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> ERRO: 2016/08/17 16:01:07.517018 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Service: Get https://192.168.0.1:443/api/v1/services?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> WARN: 2016/08/17 16:01:11.021912 Docker reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:11.022828 Endpoint reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:11.022914 Process reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:11.217168 Process reporter took 1.700674406s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:11.516470 Docker reporter took 1.999262891s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:12.318173 Endpoint reporter took 2.900963447s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:26.518115 background /proc reader: full pass took 15.495076066s: 50% more than expected (10s)
<probe> ERRO: 2016/08/17 16:01:27.216444 conntrack stderr:WARNING: We have hit ENOBUFS! We are losing events.
<probe> ERRO: 2016/08/17 16:01:27.216512 conntrack stderr:This message means that the current netlink socket buffer size is too small.
<probe> ERRO: 2016/08/17 16:01:27.216522 conntrack stderr:Please, check --buffer-size in conntrack(8) manpage.
<probe> ERRO: 2016/08/17 16:01:27.216530 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Operation failed: No buffer space available
<probe> ERRO: 2016/08/17 16:01:27.416339 conntrack error: EOF
<probe> INFO: 2016/08/17 16:01:27.416379 contrack exiting
<probe> ERRO: 2016/08/17 16:01:27.416455 conntrack error: exit status 1
<probe> ERRO: 2016/08/17 16:01:27.416859 conntrack stderr:WARNING: We have hit ENOBUFS! We are losing events.
<probe> ERRO: 2016/08/17 16:01:27.416908 conntrack stderr:This message means that the current netlink socket buffer size is too small.
<probe> ERRO: 2016/08/17 16:01:27.416923 conntrack stderr:Please, check --buffer-size in conntrack(8) manpage.
<probe> ERRO: 2016/08/17 16:01:27.416931 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Operation failed: No buffer space available
<probe> ERRO: 2016/08/17 16:01:27.617160 conntrack error: EOF
<probe> INFO: 2016/08/17 16:01:27.617197 contrack exiting
<probe> ERRO: 2016/08/17 16:01:27.716419 conntrack error: exit status 1
<probe> WARN: 2016/08/17 16:01:39.917115 Host reporter took 1.099650083s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:40.016565 K8s reporter took 1.100143003s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:40.116687 Docker reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:40.116771 Host reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:40.116807 Endpoint reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:40.216543 K8s reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:40.517178 Process reporter took longer than 1s
<probe> WARN: 2016/08/17 16:01:40.716617 Process reporter took 1.700190474s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:40.717091 Docker reporter took 1.898048674s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:43.916968 Endpoint reporter took 5.099474346s (longer than 1s)
<probe> ERRO: 2016/08/17 16:01:46.817126 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.ReplicationController: Get https://192.168.0.1:443/api/v1/replicationcontrollers?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> ERRO: 2016/08/17 16:01:47.116510 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Node: Get https://192.168.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> ERRO: 2016/08/17 16:01:47.816975 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Pod: Get https://192.168.0.1:443/api/v1/pods?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> WARN: 2016/08/17 16:01:47.816980 background /proc reader: full pass took 20.198698657s: 50% more than expected (10s)
<probe> ERRO: 2016/08/17 16:01:47.817175 Kubernetes reflector: github.com/weaveworks/scope/probe/kubernetes/client.go:119: Failed to list *api.Service: Get https://192.168.0.1:443/api/v1/services?resourceVersion=0: dial tcp 192.168.0.1:443: i/o timeout
<probe> WARN: 2016/08/17 16:01:55.217138 Docker tagger took 1.200146053s (longer than 1s)
<probe> WARN: 2016/08/17 16:01:55.617968 Docker tagger took longer than 1s
<probe> WARN: 2016/08/17 16:02:03.417898 Topology tagger took longer than 1s
<probe> WARN: 2016/08/17 16:02:04.116882 Topology tagger took 2.09988084s (longer than 1s)
<probe> WARN: 2016/08/17 16:02:04.117414 background /proc reader: full pass took 16.100917113s: 50% more than expected (10s)
<probe> WARN: 2016/08/17 16:02:08.916638 Process reporter took longer than 1s
<probe> WARN: 2016/08/17 16:02:09.016705 Endpoint reporter took longer than 1s
<probe> WARN: 2016/08/17 16:02:10.017899 Process reporter took 2.301296245s (longer than 1s)
<probe> WARN: 2016/08/17 16:02:10.516874 Endpoint reporter took 2.800414626s (longer than 1s)
<probe> ERRO: 2016/08/17 16:02:13.516494 conntrack stderr:WARNING: We have hit ENOBUFS! We are losing events.
<probe> ERRO: 2016/08/17 16:02:13.516588 conntrack stderr:This message means that the current netlink socket buffer size is too small.
<probe> ERRO: 2016/08/17 16:02:13.516600 conntrack stderr:Please, check --buffer-size in conntrack(8) manpage.
<probe> ERRO: 2016/08/17 16:02:13.516611 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Operation failed: No buffer space available
<probe> ERRO: 2016/08/17 16:02:13.617311 conntrack error: EOF
<probe> INFO: 2016/08/17 16:02:13.617354 contrack exiting
<probe> ERRO: 2016/08/17 16:02:13.617434 conntrack error: exit status 1
<probe> ERRO: 2016/08/17 16:02:13.816459 conntrack stderr:WARNING: We have hit ENOBUFS! We are losing events.
<probe> ERRO: 2016/08/17 16:02:13.816537 conntrack stderr:This message means that the current netlink socket buffer size is too small.
<probe> ERRO: 2016/08/17 16:02:13.816550 conntrack stderr:Please, check --buffer-size in conntrack(8) manpage.
<probe> ERRO: 2016/08/17 16:02:13.816559 conntrack stderr:conntrack v1.4.3 (conntrack-tools): Operation failed: No buffer space available
<probe> ERRO: 2016/08/17 16:02:14.417446 conntrack error: EOF
<probe> INFO: 2016/08/17 16:02:14.417489 contrack exiting
<probe> ERRO: 2016/08/17 16:02:14.417568 conntrack error: exit status 1
<probe> WARN: 2016/08/17 16:02:17.816718 K8s reporter took longer than 1s
<probe> WARN: 2016/08/17 16:02:17.819590 Process reporter took 2.502038466s (longer than 1s)
<probe> WARN: 2016/08/17 16:02:17.821000 Endpoint reporter took longer than 1s
<probe> WARN: 2016/08/17 16:02:17.821085 Docker reporter took longer than 1s
<probe> WARN: 2016/08/17 16:02:17.821117 Process reporter took longer than 1s
<probe> WARN: 2016/08/17 16:02:18.116581 K8s reporter took 2.700207199s (longer than 1s)
<probe> WARN: 2016/08/17 16:02:18.116983 Docker reporter took 2.799885343s (longer than 1s)
<probe> WARN: 2016/08/17 16:02:19.517473 Endpoint reporter took 4.200393904s (longer than 1s)
```

**Comment by mindfulmonk** [comment] 2016-08-17 16:12
Might be related to https://github.com/weaveworks/scope/issues/1137

**Comment by 2opremio** [comment] 2016-08-17 17:11
@mindfulmonk It seems that the probe is really tight on CPU, causing the conntrack buffers to fill up. Note all the `reporter took longer than` messages.

Where are you running this? Can you get more CPU?

**Comment by 2opremio** [comment] 2016-08-17 17:15
If you think that the problem isn't the lack of CPU but the amount of CPU consumed by Scope could you try get us a CPU profile of the probe? The profiling section at https://www.weave.works/docs/scope/latest/building/ indicates how to do it

**Comment by 2opremio** [comment] 2016-08-19 10:23
@mindfulmonk Any updates?

**Comment by 2opremio** [comment] 2016-08-22 13:33
@mindfulmonk Ping.

I will close this in a few days if there's no extra input.

**Comment by mindfulmonk** [comment] 2016-08-24 11:17
Please close, I think it was a one off.

**Closed** 2016-08-24 11:18 UTC
