### ISSUE TITLE
Scope graph doesn't show all connections between containers

### ISSUE THREAD

**Issue by mjlodge** [weaveworks/scope#1934] opened 2016-10-18 16:42 UTC
Running Sock Shop demo app, Scope does not show all the network connections between containers even though TCP network traffic is flowing.

To reproduce on Docker Mac: start Docker, follow instructions to clone sockshop github repo, cd to docker-only directory. Edit last line of compose yaml file to be "-r 10000". Do `docker-compose up -d`

Wait about 30s for the traffic generator container to start. Observe that only a few containers show connections between them, even though the user-sim container is firing off requests to the app.

Only when large amounts of requests are flowing do connections start to show up. Do `docker-compose scale user-sim=5` for example. Note that you will have to hit the refresh icon several times to get the graph to change.

cc @pidster

**Comment by mjlodge** [comment] 2016-10-18 16:43
![screenshot 2016-10-17 10 44 00](https://cloud.githubusercontent.com/assets/2354066/19487349/4add4cce-9517-11e6-9dc9-cde62e97ece4.png)
![screenshot 2016-10-17 11 35 15](https://cloud.githubusercontent.com/assets/2354066/19487361/568c6d70-9517-11e6-970a-4d0e8519168c.png)

**Comment by 2opremio** [comment] 2016-10-18 16:46
Can you provide us with the log of the scope probe? `docker logs weavescope`

**Comment by mjlodge** [comment] 2016-10-18 20:44
`Mathews-Macbook-2:docker-only mathewlodge$ docker logs weavescope
<probe> INFO: 2016/10/18 20:43:07.638568 command line args: --logtostderr=true --mode=probe --probe.docker=true --service-token=<elided>
<probe> INFO: 2016/10/18 20:43:07.639475 probe starting, version 0.17.1, ID 79e59343e26cc1db
<probe> INFO: 2016/10/18 20:43:07.639527 publishing to: cloud.weave.works:443
<probe> ERRO: 2016/10/18 20:43:07.787325 conntrack: failed to find module nf_conntrack
<probe> INFO: 2016/10/18 20:43:07.787700 Not using conntrack: module not present
<probe> ERRO: 2016/10/18 20:43:07.787943 conntrack: failed to find module nf_conntrack
<probe> INFO: 2016/10/18 20:43:07.788138 Not using conntrack: module not present
<probe> INFO: 2016/10/18 20:43:08.372996 Success collecting weave status
<probe> INFO: 2016/10/18 20:43:08.665024 Control connection to 52.206.83.218:443 starting
<probe> INFO: 2016/10/18 20:43:11.148889 Publish loop for 52.206.83.218:443 starting
<probe> INFO: 2016/10/18 20:43:11.306198 Success collecting weave ps
<probe> ERRO: 2016/10/18 20:43:24.353186 Error doing publish for 52.206.83.218:443, backing off 1s: Post https://52.206.83.218:443/api/report: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
<probe> ERRO: 2016/10/18 20:44:03.923058 Error doing publish for 52.206.83.218:443, backing off 1s: Post https://52.206.83.218:443/api/report: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
`

**Comment by mjlodge** [comment] 2016-10-18 21:16
Here's another example running on ECS:
![screenshot 2016-10-18 14 14 48](https://cloud.githubusercontent.com/assets/2354066/19496684/7440cb06-953d-11e6-8b45-95e7d9795771.png)

**Comment by ekimekim** [comment] 2016-10-18 21:32
> ERRO: 2016/10/18 20:44:03.923058 Error doing publish for 52.206.83.218:443, backing off 1s: Post https://52.206.83.218:443/api/report: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Anecdotally, I've been seeing a ton of these errors too. I think there might be something wrong with the client, because there's no way it should be hitting that timeout in normal operation. Only one out of every few reports getting through would go a long way to explaining some of the weird behaviour we've been seeing.

**Comment by 2opremio** [comment] 2016-10-20 16:33
@mjlodge Here's the problem

```
ERRO: 2016/10/18 20:43:07.787943 conntrack: failed to find module nf_conntrack
INFO: 2016/10/18 20:43:07.788138 Not using conntrack: module not present
```

Without conntrack, short lived connections cannot currently be tracked. It could be that Docker4Mac supports conntrack but we are not detecting it properly, which is fixed in master (only 1 day after the 0.17.1 release)

**Comment by 2opremio** [comment] 2016-10-20 16:36
Yep, that's the problem. You can use `weaveworks/scope:latest` as a workaround until the next release of Scope.

```
manzanon:weave fons$ docker run -ti --rm busybox 
/ # cat /proc/sys/net/netfilter/nf_conntrack_tcp_timeout_close
10
```

**Comment by 2opremio** [comment] 2016-10-20 16:39
Duplicate of #1826

**Comment by 2opremio** [comment] 2016-10-21 11:53
@mjlodge Could you try with `weaveworks/scope:latest` (using the scope script from master https://raw.githubusercontent.com/weaveworks/scope/master/scope ) and see if things work as you expect?

**Closed** 2016-11-09 16:26 UTC
Labels: bug
