### ISSUE TITLE
If eBPF fails to start we should fallback to proc parsing and conntrack

### ISSUE THREAD

**Issue by alepuccetti** [weaveworks/scope#2243] opened 2017-02-15 09:46 UTC
As a follow-up work on https://github.com/weaveworks/scope/pull/2135 we should fallback to `/proc` parsing and `conntrack` if ebpf fails to start. One of the causes could be that the kernel is compiled without eBPF support.

**Comment by 2opremio** [comment] 2017-03-05 12:36
Duplicate of #2215

**Closed by 2opremio** 2017-03-05 12:36 UTC
Labels: chore
