### ISSUE TITLE
dns rate limiting hard-coded to 10s, causing havoc when app window is smaller

### ISSUE THREAD

**Issue by rade** [weaveworks/scope#1128] opened 2016-03-05 10:06 UTC
I am running with an app.window of 5s and see a lot of instability in the 'BY DNS NAME' view, with nodes frequently disappearing.

I reckon the cause of that is similar to #1122, i.e. a hard-coded polling interval of 10s, this time at https://github.com/weaveworks/scope/blob/592bf3fb4355cf3fae9cefc4dbb3fc0de75c12da/probe/appclient/resolver.go#L16.

**Comment by rade** [comment] 2016-03-05 10:27
Hmm. I am seeing this behaviour even with the standard app.window. And it doesn't go away when I lower the hard-coded interval to 1s. So there might be something else going on here.

**Comment by tomwilkie** [comment] 2016-03-05 14:29
Yes, the reverse dba resolution is currently not used in the rendering
pipeline (I jut opened a bug about this).  Also, the reverse lookups use a
cache so should be pretty stable.

The problem here is one of Paul's pet peeves and is due to how we merge
nodes in the rendering pipe line. There is already a bug about this.

**Comment by tomwilkie** [comment] 2016-04-19 15:08
Paul + I believe this is actually a dupe of #1130

**Closed by tomwilkie** 2016-04-19 15:08 UTC
