### ISSUE TITLE
Disappearing pseudo-nodes leave a hanging edge

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1334] opened 2016-04-18 15:02 UTC
Internet node was present, but then disappeared. The edge to it stayed. Attached report, canvas svg, and `/api/topology/containers` output, but I doubt they'll be helpful in this case, as when I refreshed the edge went away.

![screen shot 2016-04-18 at 15 58 07](https://cloud.githubusercontent.com/assets/250199/14608665/93cafe14-057e-11e6-9bb4-a9d96ed9aaf9.png)
[report_missing_node.zip](https://github.com/weaveworks/scope/files/224043/report_missing_node.zip)

**Comment by tomwilkie** [comment] 2016-04-19 14:47
I have also seen this happen.

**Comment by tomwilkie** [comment] 2016-04-19 14:54
Dupe of #1304

**Closed by tomwilkie** 2016-04-19 14:54 UTC
Labels: bug, ui
