### ISSUE TITLE
A lot of uncontained nodes on DC/OS

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1351] opened 2016-04-19 16:51 UTC
<img width="1561" alt="screenshot 2016-04-19 17 43 46" src="https://cloud.githubusercontent.com/assets/251467/14647579/5f098492-0656-11e6-84b5-f6919051a0f6.png">

[Report](https://github.com/errordeveloper/scope-report-store/blob/master/report-2016-04-19-17-50-09.json)

**Comment by errordeveloper** [comment] 2016-04-19 16:52
These are clearly some kind of system-level processes, would be nice to figure out and classify those a bit better.

**Comment by tomwilkie** [comment] 2016-04-20 16:20
Dupe of #1129

**Closed by tomwilkie** 2016-04-20 16:20 UTC
