### ISSUE TITLE
Add controls and pipes (terminal/logs) for hosts

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1049] opened 2016-02-26 16:07 UTC
This will greatly simplify administration tasks.

For logs we could use journalctl (or syslog).

**Comment by tomwilkie** [comment] 2016-02-26 16:11
Dupe of #1016 (tty for host)?

What controls can you think of for a host?

**Comment by 2opremio** [comment] 2016-02-26 16:16
> Dupe of #1016 (tty for host)?

Partly, I edited the description to include logs too.

**Comment by tomwilkie** [comment] 2016-02-26 16:24
What are host logs?  Unlike a container, there is very little standardisation here.   I'd say just offer a shell and allow people to `tail -f /var/log/messages` in them.

**Comment by tomwilkie** [comment] 2016-02-29 18:37
I'm going to close as dupe of #1016 here.

**Comment by 2opremio** [comment] 2016-02-29 19:51
Please don't close this before at least create a separate ticket for the logs.

> What are host logs? Unlike a container, there is very little standardisation here. I'd say just offer a shell and allow people to tail -f /var/log/messages in them.

I think we can potentially do better than that.

**Closed** 2016-07-04 12:31 UTC
Labels: dogfood
