### ISSUE TITLE
Scope views lose ability to zoom in and out when node is clicked on

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#2848] opened 2017-09-08 21:51 UTC
**Cloud/OS:** Digital Ocean/ Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-79-generic x86_64)
**Kubernetes: Client Version:** version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", **GitCommit:**"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T07:00:21Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}

**App:** Sockshop running
**Browser OS**: Chrome Version 60.0.3112.113 (Official Build) (64-bit) / Mac OS sierra

To reproduce: 

1.  Click on Explore --> Pods and then use the mouse to zoom in. 
2. Click on a pod to display the details panel. 
3. Note that view is already distorted and all pods freeze. 
4. Close the details panel and go to Hosts

Note: that you can no longer zoom in and out on the view and it needs to be reset. 

http://recordit.co/6yWR2RWFxW

**Comment by abuehrle** [comment] 2017-09-08 21:53
When zoom fails, the nodes and arrows appear like so: 

![screen shot 2017-09-08 at 4 52 23 pm](https://user-images.githubusercontent.com/13420383/30232543-32e377c0-94b6-11e7-9fb2-171e56e5054b.png)

**Comment by rade** [comment] 2017-09-11 09:42
Here's what I am seeing on dev-on-prod, on Chrome

![screenshot from 2017-09-11 10-40-43](https://user-images.githubusercontent.com/109109/30268486-c5767b04-96dd-11e7-9302-155edea03e4c.png)

cc @foot @fbarl I wonder whether this got broken in the recent ff/chrome zoom level alignment changes.

**Comment by rade** [comment] 2017-09-11 09:57
I am also experiencing the freezing. And the zoom controls, including the slider, not working.

**Comment by rade** [comment] 2017-09-11 10:08
Ouch. Something is very broken here.

1. Go to https://cloud.weave.works/app/loud-breeze-77
2. reset the view state via the 'bug' menu in the bottom right
3. click on graph view

This results in something like
![screenshot from 2017-09-11 11-05-15](https://user-images.githubusercontent.com/109109/30269606-4dbcc43e-96e1-11e7-85a4-422cd8db51c2.png)
This is zoomed in way too far. Also, the zoom control in the bottom right doesn't work. And occasionally all the edges disappear.

I am seeing this in Chrome and FF.

**Comment by sambooo** [comment] 2017-09-11 10:30
My findings from testing on the big three browsers on Sierra:

*Firefox*: Stuck zoomed all the way in. Neither slider nor mousewheel work. Panning works. Edges sometimes disappear.

*Safari*: Page loads zoomed all the way in. Mousewheel works, slider doesn't. Panning works. Edges sometimes disappear.

*Chrome*: Page loads zoomed all the way in. Mousewheel and slider work. Panning works.

**Comment by fbarl** [comment] 2017-09-11 13:29
Everything seems to be fixed now after bumping back the Scope UI version that was accidentally downgraded in https://github.com/weaveworks/service-ui/commit/7b2b46088575757e1affd0949e94be699710156a#diff-52dbbf94d5c54b68c0cad0702ba94a96.

The only thing that is still there and it seems to be an unrelated issue that's been there for a while is edges occasionally disappearing - I'll create a separate issue for that.

@abuehrle @rade @sambooo feel free to test the dev on your platforms before I close this issue.

**Comment by rade** [comment] 2017-09-11 13:56
Works in in dev.

**Comment by abuehrle** [comment] 2017-09-12 22:09
Ilya ran into this at his demo last night.   @mewzherder @errordeveloper

**Comment by rade** [comment] 2017-09-13 03:17
> Ilya ran into this at his demo last night.

Where "it" is "zoom not working"? And this was on cloud.weave.works? Can you reproduce this, @abuehrle?

**Comment by abuehrle** [comment] 2017-09-13 09:33
> Where "this" is "zoom not working"? And this was on cloud.weave.works? Can you reproduce this, 

Maybe @errordeveloper will see it again when he runs through his TensorFlow demo today. Could be after deploying?

**Comment by rade** [comment] 2017-09-14 06:34
I am closing this until somebody can reproduce it.

**Closed by rade** 2017-09-14 06:34 UTC
Labels: bug, component/ui
