### ISSUE TITLE
Node animation lags behind edge animation

### ISSUE THREAD

**Issue by tomwilkie** [weaveworks/scope#1242] opened 2016-04-07 11:11 UTC
(Discussed on a hangout with @davkal)

**Comment by davkal** [comment] 2016-04-07 11:13
Can reproduce with debug toolbar...

**Comment by davkal** [comment] 2016-04-07 16:23
This happens when new edges are created that connect to nodes that are moving to a new position. Those edges currently dont animate because they have no prior state.

A possible fix would be passing the source and target nodes from a previous layout run (cant be the current state because those are the final positions) to the edge and injecting those coords as prior waypoints into the edge (via react-motion's `defaultStyle`).

This is not a regression, seen in 0.13, removing milestone.

**Comment by tomwilkie** [comment] 2016-04-11 17:01
I've seen this when no new edges are coming in; just by clicking the redraw button.

**Closed** 2016-04-12 07:35 UTC
Labels: bug, ui
