### ISSUE TITLE
Unexpected edges being rendered

### ISSUE THREAD

**Issue by 2opremio** [weaveworks/scope#1405] opened 2016-04-29 00:07 UTC
Maybe a duplicate of https://github.com/weaveworks/scope/issues/520 but I have a consistent way to reproduce it:

```
# create kubernetes cluster
(cd service && infra/local-k8s up )

git clone git@github.com:2opremio/craft-kubernetes-workshop.git 
cd craft-kubernetes-workshop/kubernetes
kubectl create secret generic tls-certs --from-file=tls
kubectl create configmap nginx-frontend-conf --from-file=nginx/frontend.conf
kubectl create -f deployments/hello.yaml
kubectl create -f services/hello.yaml
kubectl create -f deployments/auth.yaml
kubectl create -f services/auth.yaml 
kubectl create -f deployments/frontend.yaml
kubectl create -f services/frontend.yaml 

curl https://github.com/tsenart/vegeta/releases/download/v6.1.0/vegeta-v6.1.0-linux-amd64.tar.gz
tar -xvzf vegeta-v6.1.0-linux-amd64.tar.gz
echo "GET https://$(kubectl get service  frontend  --template '{{.spec.clusterIP}}')" | ./vegeta attack -connections 1  -insecure -duration 0 -rate 20  > /dev/null
```

You will get edges from the nginx container to kubernetes components to between which there is no communication. For instance:

<img width="1735" alt="screen shot 2016-04-29 at 01 00 18" src="https://cloud.githubusercontent.com/assets/2362916/14905157/fd4d35bc-0da5-11e6-8fb9-8630cd5930d5.png">

nginx is not talking to `apiserver`, `scheduler` nor `controllermanager`. Sometimes it also gets edges to `etcd`.

Report: 
[report_madeup_edges.json.gz](https://github.com/weaveworks/scope/files/241612/report_madeup_edges.json.gz)

**Comment by tomwilkie** [comment] 2016-05-03 16:18
I think we should close this as a dupe of #520; we have plenty of ways of reproducing it.  @2opremio  thoughts?

**Closed** 2016-05-04 11:43 UTC
Labels: bug, k8s
