### ISSUE TITLE
Incorrect height of terminal window in Safari

### ISSUE THREAD

**Issue by pidster** [weaveworks/scope#1986] opened 2016-11-04 17:30 UTC
When launching the terminal control on a SockShop container in Safari (Version 10.0.1 (12602.2.14.0.7)), the height of the internal window is very small - barely 1 character high.

Chrome works OK. See screenshot below.

<img width="1237" alt="safari-scope" src="https://cloud.githubusercontent.com/assets/303151/20015695/557dd270-a2b4-11e6-98a0-ea2780101d63.png">

**Comment by 2opremio** [comment] 2016-11-04 17:31
As a reminder please create a PR on top of branch `release-1.0` if you manage to fix this today.

**Comment by jpellizzari** [comment] 2016-11-04 19:23
Root cause of this appears to be Safari measuring `innerNode.clientHeight` differently from Chrome:
https://github.com/weaveworks/scope/blob/master/client/app/scripts/components/terminal.js#L274

**Comment by foot** [comment] 2016-11-07 11:58
Fixed in #1988

**Closed by foot** 2016-11-07 11:58 UTC
Labels: bug
