### ISSUE TITLE
Performance issues are hard to notice

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#1467] opened 2016-05-10 14:31 UTC
We keep catching them just before release, but we should spot them earlier.

Suggestion is to spin up a k8s cluster somewhere (gce?) and run a test with BigData(tm), on it on every merge to master (or nightly, or something)...

**Comment by 2opremio** [comment] 2016-05-10 14:40
Duplicate of (or at least related to) #1406

**Closed** 2016-05-10 14:50 UTC
Labels: k8s, performance, techdebt
