### ISSUE TITLE
Icon is non-obvious

### ISSUE THREAD

**Issue by paulbellamy** [weaveworks/scope#159] opened 2015-06-02 15:08 UTC
I don't understand what this toggle does.. It seems to change the node descriptions somehow?
![screen shot 2015-06-02 at 16 06 16](https://cloud.githubusercontent.com/assets/250199/7939159/6a721a3c-0941-11e5-8e94-6cc455458bb6.png)

**Comment by peterbourgon** [comment] 2015-06-02 17:09
It's toggles grouping, e.g. show individual containers (left), or group all containers that run the same image (right). Maybe better icons would be like (⣿) vs (⸫)? The point is to represent different levels of granularity. What would you suggest, if anything?

**Comment by peterbourgon** [comment] 2015-06-02 17:10
This is a duplicate of #156 so I'll close it in favor of that one...

**Closed by peterbourgon** 2015-06-02 17:10 UTC
