### ISSUE TITLE
"invalid id:" stats gathering error in logs

### ISSUE THREAD

**Issue by shamil** [weaveworks/scope#1857] opened 2016-09-12 13:29 UTC
Hi,

weavescope version: `0.17.1`
kubernetes version: `1.3.6`
docker version

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:39 2016
 OS/Arch:      linux/amd64
```

I get lots of errors in docker logs when `probe` process runs in kubernetes. 

```
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.038475237Z" level=error msg="collecting stats for b1417c66b2512b55fb079b5815e86b5611eb125a29100b7a2d4583e44325c575: invalid id: "
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.041059139Z" level=error msg="collecting stats for d014c832df96fa39ffb91d7880be85024f3a627527f90141f4736f3c52613a0b: invalid id: "
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.743684587Z" level=error msg="collecting stats for d014c832df96fa39ffb91d7880be85024f3a627527f90141f4736f3c52613a0b: invalid id: "
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.927764315Z" level=error msg="collecting stats for d55624b69447994c622b681618115b585e9381348f4bd67cbcea6c397a8f5918: invalid id: "
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.928994551Z" level=error msg="collecting stats for e9c6efe47462e159d66b71966c7a0728a24dad3acd36a97d6e6d534a3ea4a85a: invalid id: "
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.930907055Z" level=error msg="collecting stats for e1db58d26cf14b0531bad29d9ada1262b6bdebc9c31ca04289eb62735ef1443c: invalid id: "
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.932262728Z" level=error msg="collecting stats for bb4352d1ab491268cf215416be9f5d6755a785026e2d36769def2a00761b100b: invalid id: "
Sep 12 13:26:05 ip-10-100-66-180 docker[6393]: time="2016-09-12T13:26:05.933434308Z" level=error msg="collecting stats for 999295c8ef123c664d860ef9a307fa65a6658868e5d1525148b151af89f17a38: invalid id: "
```

Once I stop the `probe` PODs the error goes away.

`probe` args

```
--no-app
--probe.docker.bridge=cbr0
--probe.docker=true
--probe.kubernetes=true
--probe.conntrack=false
--probe.proc.spy=false
--probe.processes=false
--weave=false
$(WEAVESCOPE_APP_SERVICE_HOST):$(WEAVESCOPE_APP_SERVICE_PORT)
```

**Comment by rade** [comment] 2016-09-12 13:39
I am guessing the containers in question are very short-lived and have vanished by the time scope tries to collect stats for them. The error is harmless, but we should really suppress it.

**Comment by shamil** [comment] 2016-09-12 13:46
@rade, 
The errors comes from `docker` logs not from `weavescope`. The containers runs are not short-lived they up for hours even days.

**Comment by rade** [comment] 2016-09-12 13:53
> The errors comes from docker logs not from `weavescope`.

Are there any errors in the `weavescope` logs? I rather suspect you'll find similar errors there.

> The containers runs are not short-lived they up for hours even days.

Both k8s and scope create short-lived internal (i.e. nothing to do with your app) containers. To check, see whether any of the container IDs mentioned in the logs do in fact exist. I rather suspect they don't (anymore).

If the problem is what I think it is then there is nothing we can do about it. But, as I said, it's harmless.

**Comment by shamil** [comment] 2016-09-12 14:07
Don't think kubernets creates short-lived containers without reason. At least not in my case. I don't use any special resources, like `jobs` or `autoscaler`, etc ...

If I actually take one of the ids from the above log, I can see that those containers are up and running for long time, so I'm 100% positive it's not related to short-lived or not.

In the `weavescope` log I don't see anything special, here is the output since it was started:

```
<probe> INFO: 2016/09/12 11:01:49.200915 command line args: --logtostderr=true --mode=probe --no-app=true --probe.conntrack=false --probe.docker=true --probe.docker.bridge=cbr0 --probe.kubernetes=true --probe.proc.spy=false --probe.processes=false --weave=false 100.67.127.179:80
<probe> INFO: 2016/09/12 11:01:49.200997 probe starting, version 0.17.1, ID 7fa4cdfa80971b0d
<probe> INFO: 2016/09/12 11:01:49.201011 publishing to: 100.67.127.179:80
<probe> INFO: 2016/09/12 11:01:49.204233 Control connection to 100.67.127.179:80 starting
<probe> INFO: 2016/09/12 11:01:49.226009 kubernetes: targeting api server https://100.64.0.1:443
<probe> ERRO: 2016/09/12 11:01:49.481500 plugins: problem loading: no such file or directory
<probe> INFO: 2016/09/12 11:01:52.538183 Publish loop for 100.67.127.179:80 starting
```

**Comment by shamil** [comment] 2016-09-12 14:09
Also you said the logs are harmless, I have no objections, but when you get about 10th of those messages per second you should start to worry, no?

**Comment by rade** [comment] 2016-09-12 14:13
Hmm doesn't look the problem is what I thought it was. Could be a docker bug; there was a problem with stats, especially in the context of k8s, pre 1.12 - see #1291.

**Comment by rade** [comment] 2016-09-13 09:54
@shamil can you try docker 1.12.1?

**Comment by rade** [comment] 2017-01-10 23:57
closing. if somebody can repro this with Docker >=1.12 then re-open.

**Closed by rade** 2017-01-10 23:57 UTC
Labels: chore

**Comment by adesaegher** [comment] 2017-01-18 15:17
Got lots of lines like this one on 1.12.5 on centos7 (No problem on 1.12.3) :
docker: time="2017-01-18T16:04:28.671968138+01:00" level=error msg="collecting stats for 1d1cc403eebd5a50e3e6bed9bfb4591f83c019b55e1a38253d7bc86f95c61968: sandbox 5165aa0643a7b47353183f92306fcbc145440251a0995a1a8acda44f16b46f30 not found"

**Comment by sebglon** [comment] 2017-01-19 10:45
docker/docker#30274
