### ISSUE TITLE
Cannot get more details about process

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#2909] opened 2017-10-24 20:36 UTC
When I look at processes by name and bring up details panel, processes in the list are not clickable, so I cannot bring up details panel for each of them – I'd like to know e.g. which host is it on.
<img width="1666" alt="screenshot 2017-10-24 21 34 24" src="https://user-images.githubusercontent.com/251467/31966772-adc6e654-b903-11e7-9835-9fa05d4993cc.png">

**Comment by rade** [comment] 2017-12-08 17:12
This does work for me, e.g.
![screenshot from 2017-12-08 17 11 27](https://user-images.githubusercontent.com/109109/33776939-e0998dde-dc3a-11e7-83fd-27fb9963c43f.png)

@errordeveloper how can I reproduce what you are seeing?

**Comment by errordeveloper** [comment] 2017-12-13 15:53
Ok, this must be to do with the relative path (`./kubelet`), which is not very usual... Also, perhaps we could ignore the original case for the moment as it's a Mesos container and we don't fully support it yet.

So I've just had a look at Sock Shop stagings, and can see that we link to process in some cases, e.g.:

- [payment](https://cloud.weave.works/app/little-meadow-46#!/state/{"controlPipe":null,"nodeDetails":[{"id":"weaveworksdemos<SLASH>payment;<container_image>","label":"weaveworksdemos<SLASH>payment","topologyId":"containers-by-image"}],"pausedAt":null,"topologyViewMode":"grid","pinnedMetricType":null,"pinnedSearches":[],"searchQuery":"","selectedNodeId":"weaveworksdemos<SLASH>payment;<container_image>","gridSortedBy":"containers-by-image","topologyId":"containers-by-image","topologyOptions":{"processes":{"unconnected":["hide"]},"containers":{"system":["application"],"stopped":["running"],"pseudo":["hide"],"namespace":[""]},"pods":{"pseudo":["hide"],"namespace":[""]}},"contrastMode":false})
- [catalogue](https://cloud.weave.works/app/little-meadow-46#!/state/{"controlPipe":null,"nodeDetails":[{"id":"weaveworksdemos<SLASH>catalogue-db;<container_image>","label":"weaveworksdemos<SLASH>catalogue-db","topologyId":"containers-by-image"}],"pausedAt":null,"topologyViewMode":"grid","pinnedMetricType":null,"pinnedSearches":[],"searchQuery":"","selectedNodeId":"weaveworksdemos<SLASH>catalogue-db;<container_image>","gridSortedBy":"containers-by-image","gridSortedDesc":null,"topologyId":"containers-by-image","topologyOptions":{"processes":{"unconnected":["hide"]},"containers":{"system":["application"],"stopped":["running"],"pseudo":["hide"],"namespace":[""]},"pods":{"pseudo":["hide"],"namespace":[""]}},"contrastMode":false})
But we do not

**Comment by rade** [comment] 2017-12-13 15:58
> this must be to do with the relative path

Doubt it.

Not all processes are linkable. See #991.

**Comment by rade** [comment] 2017-12-13 17:42
The missing links in sock-shop are due to #991. I am going to close this as a dup of that.

**Closed by rade** 2017-12-13 17:42 UTC
Labels: bug
