### ISSUE TITLE
Some containers do not have sparklines

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#1883] opened 2016-09-23 07:54 UTC
This container has spark lines:
![](https://www.dropbox.com/s/1eb3jv8nsf99yng/Screenshot%202016-09-23%2008.52.11.png?dl=1)

And this one doesn't:
![](https://www.dropbox.com/s/yew3og8cbgc2sig/Screenshot%202016-09-23%2008.52.05.png?dl=1)

And `docker stats ac4168320938`:
![](https://www.dropbox.com/s/6r7naxb9hfnl6r7/Screenshot%202016-09-23%2008.53.29.png?dl=1)

cc @2opremio

**Comment by rade** [comment] 2016-09-23 11:25
What docker version you are running? There is a problem with stats pre 1.12.

**Comment by errordeveloper** [comment] 2016-09-23 18:27
It is 1.11.2, which is what Kubernetes 1.4 will stick to as well.

**Comment by rade** [comment] 2016-09-23 18:42
> It is 1.11.2, which is what Kubernetes 1.4 will stick to as well.

Ouch, that sucks. I suspect we are probably stuck then. See #1291 for a description of the problem. IF this is indeed that problem...

I am guessing your drone_build container isn't running inside a pod (hence it shows stats), but sick_darwin is (hence it doesn't). Can you confirm that?

**Comment by errordeveloper** [comment] 2016-09-23 18:48
No, sick_darwin I spun up by Drone CI, so it is not in a pod, also pods
don't have such name. I will need to look what kind of container is it, may
be it is not a plain 'docker run', if that could make any difference.

**Comment by rade** [comment] 2016-09-23 18:56
The fact that `docker stats` returns zero values does look a lot like #1291.

**Comment by 2opremio** [comment] 2016-12-13 08:56
@errordeveloper Is this still a problem with recent kubernetes versions. I am with @rade on this being caused by docker returning zero stats.

**Comment by rade** [comment] 2016-12-13 09:43
The [kubernetes 1.5 changelog says](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information)
> Docker versions 1.10.3 - 1.12.3

I have been unable to find out what versions of docker ship / are deployed with the myriads of ways of installing k8s.

**Comment by rade** [comment] 2017-01-10 22:53
In the absence of a recent repro by @errordeveloper I am closing this.

**Closed by rade** 2017-01-10 22:53 UTC
Labels: bug
