### ISSUE TITLE
Filtering from Image to Name causes flickering

### ISSUE THREAD

**Issue by abuehrle** [weaveworks/scope#1656] opened 2016-07-07 18:17 UTC
When you switch context going between or within views, or from Name to Image in the Processes View, or in the Container view, the screen flashes the "nothing here" circle before filtering by images.  

I noticed this in VERSION b89e9ecON

**Comment by rade** [comment] 2016-08-25 01:27
I am not seeing this. I get a brief blank (modulo controls) canvas, but no "nothing here" circle.

**Comment by rade** [comment] 2016-12-12 07:51
@davkal has anybody managed to reproduce this?

**Comment by davkal** [comment] 2016-12-12 10:09
> has anybody managed to reproduce this?

@fbarl could you give this a try?

**Comment by fbarl** [comment] 2016-12-12 11:00
Yup, I was able to reproduce it multiple times when switching from `BY NAME` to `BY IMAGE` view of processes. It really happens in a blink of an eye, but I managed to catch a screenshot before the topology is rendered:

![screenshot from 2016-12-12 11-53-04](https://cloud.githubusercontent.com/assets/1216874/21096913/38f7a7fe-c062-11e6-98ea-f37811de8f6a.png)

@davkal I can take a look into it this afternoon.

**Comment by fbarl** [comment] 2016-12-12 14:52
Hmm... After doing some more testing, I couldn't reproduce the problem on `dev` nor `production`.

The problem appears for me only locally after resetting `scope` (e.g. by loading a report) while keeping the Scope UI running without refreshing the page. Only then I'm able to reproduce it by clicking on the `BY IMAGE` view that pops up under `PROCESSES` (as on the screenshot above), but according to `api_topologies.go`, that view shouldn't even be there:

```
APITopologyDesc{
	id:          processesID,
	renderer:    render.FilterUnconnected(render.ProcessWithContainerNameRenderer),
	Name:        "Processes",
	Rank:        1,
	Options:     unconnectedFilter,
	HideIfEmpty: true,
},
APITopologyDesc{
	id:          processesByNameID,
	parent:      processesID,
	renderer:    render.FilterUnconnected(render.ProcessNameRenderer),
	Name:        "by name",
	Options:     unconnectedFilter,
	HideIfEmpty: true,
},
APITopologyDesc{
	id:       containersID,
	renderer: render.ContainerWithImageNameRenderer,
	Name:     "Containers",
	Rank:     2,
	Options:  containerFilters,
},
APITopologyDesc{
	id:       containersByHostnameID,
	parent:   containersID,
	renderer: render.ContainerHostnameRenderer,
	Name:     "by DNS name",
	Options:  containerFilters,
},
APITopologyDesc{
	id:       containersByImageID,
	parent:   containersID,
	renderer: render.ContainerImageRenderer,
	Name:     "by image",
	Options:  containerFilters,
},
```

In fact, the newly added view points to the same topology as `BY IMAGE` view under `CONTAINERS`, which is supposedly a bug on its own - @davkal, I wonder if it's been referenced by an existing issue.

Since the "nothing here" bug seems to appear now only under those circumstances, I think it's safe to say it will be gone once we fix this extra view issue.

**Comment by rade** [comment] 2017-11-12 13:33
Indeed there should be no 'by image' view under processes. And I cannot see one in my testing.

-> closing

**Closed by rade** 2017-11-12 13:33 UTC
Labels: bug, component/ui, help-wanted
