### ISSUE TITLE
API path is incorrect under prefix

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/scope#2247] opened 2017-02-15 15:44 UTC
I'm trying to update DC/OS package for Scope to use version 1.2.0.

Once installed the package on DC/OS, I need to go to `https://<dcos_host>/service/weavescope`, and  the UI loads okay, but it tries to access the API on a weird URL.

The URL it tries to call is `https://<dcos_host>/api/service/weavescope/api/topology`, while it should be `/service/weavescope/api/topology`.

If I load `/service/weavescope/api/topology`, I can see the topology, while `/api/service/weavescope/api/topology` gives me a 404, as DC/OS doesn't have a route for it.

How does this `/api` get prepended? I'm looking at `getApiPath()` in  [`client/app/scripts/utils/web-api-utils.js`](https://github.com/weaveworks/scope/blob/c9048d8661a02200b76826d30f01db97e1947cbf/client/app/scripts/utils/web-api-utils.js#L61), is it the right place to look or not?

**Comment by errordeveloper** [comment] 2017-02-15 15:45
I've tested 1.1.0, and can see the same issue with it.

**Comment by jpellizzari** [comment] 2017-02-15 18:39
This was fixed in https://github.com/weaveworks/scope/pull/2202, but that PR was not merged until after the release.

**Comment by 2opremio** [comment] 2017-02-15 22:50
Duplicate of https://github.com/weaveworks/scope/issues/2154

**Closed by 2opremio** 2017-02-15 22:50 UTC
Labels: bug

**Comment by 2opremio** [comment] 2017-02-16 02:12
The fix will be released in 1.2.1, coming out imminently (#2250 )
